<span style="color: #2563eb;">📊 Guide Complet Pandas</span>
Maîtrisez la Manipulation et l'Analyse de Données avec Python

<div align="center" style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); padding: 30px; border-radius: 15px; color: white; margin: 30px 0;">
<h1 style="color: white; font-size: 2.8em; margin-bottom: 10px;">🐼 GUIDE COMPLET PANDAS</h1>
<h2 style="color: #fbbf24; font-weight: 300; margin-top: 0;">Manipulation et Analyse de Données Professionnelle avec Python</h2>
</div>

🏷️ Métadonnées du Guide
<div style="background: #f8fafc; padding: 25px; border-radius: 12px; border-left: 6px solid #3b82f6; margin: 25px 0;">
Auteur : FOFANA Lamine<br>
Email : fofanalamine039@gmail.com<br>
GitHub : [@fofanalamine](https://github.com/FOFANA-Lamine)<br>
Date de Publication : 2026<br>
Version : 1.0<br>
Dernière Mise à Jour : 01/02/2026<br><br>

Tags : Pandas Python DataAnalysis DataFrame Visualisation Jupyter Tutoriel
</div>

📋 Table des Matières
<div style="background: linear-gradient(to right, #f0f9ff, #e0f2fe); padding: 25px; border-radius: 12px; margin: 25px 0;">
🎯 Introduction et Objectifs<br>
🏗️ Structures de Données Fondamentales<br>
📁 Lecture et Écriture de Données<br>
🔍 Inspection et Exploration des Données<br>
🎯 Sélection et Indexation<br>
🛠️ Manipulation des Données<br>
📊 Agrégation et Regroupement<br>
🔗 Jointures et Combinaisons<br>
📅 Données Temporelles<br>
🏷️ Données Catégorielles<br>
⚡ Optimisation des Performances<br>
🚀 Fonctions Avancées<br>
📈 Visualisation Intégrée<br>
💡 Trucs et Astuces<br>
🔌 Intégration avec Autres Bibliothèques<br>
🎯 Exercice Final : Projet Complet d'Analyse de Ventes
</div>

🎯 Introduction et Objectifs
<div style="background: #f0fdf4; padding: 25px; border-radius: 12px; border: 2px solid #86efac; margin: 25px 0;">
<h3>Pourquoi ce Guide ?</h3>
Ce guide complet a été conçu pour vous accompagner dans la maîtrise de Pandas, la bibliothèque Python incontournable pour la manipulation et l'analyse de données. Que vous soyez data scientist, analyste, chercheur ou développeur, ce document vous fournira toutes les clés pour traiter efficacement vos données tabulaires.

🎖️ Objectifs :
✅ Comprendre les structures Series et DataFrame<br>
✅ Maîtriser la manipulation de données tabulaires<br>
✅ Effectuer des analyses statistiques avancées<br>
✅ Gérer les données temporelles et catégorielles<br>
✅ Optimiser les performances pour les gros jeux de données

📊 À qui s'adresse ce guide ?
<table style="width: 100%; border-collapse: collapse; margin-top: 20px;">
<tr style="background: #3b82f6; color: white;">
<th>Niveau</th>
<th>Public Cible</th>
<th>Prérequis</th>
</tr>
<tr style="background: #f8fafc;">
<td>👶 Débutant</td>
<td>Étudiants en data science</td>
<td>Bases Python</td>
</tr>
<tr style="background: #f1f5f9;">
<td>👨‍🎓 Intermédiaire</td>
<td>Data analysts, ingénieurs</td>
<td>Notions de base sur les données</td>
</tr>
<tr style="background: #f8fafc;">
<td>🧠 Avancé</td>
<td>Data scientists, chercheurs</td>
<td>Expérience en analyse de données</td>
</tr>
</table>
</div>

⭐ Points Forts de Pandas
<div style="display: grid; grid-template-columns: repeat(auto-fit, minmax(300px, 1fr)); gap: 20px; margin: 30px 0;">
<div style="background: white; padding: 20px; border-radius: 10px; box-shadow: 0 4px 6px rgba(0,0,0,0.1); border-top: 4px solid #3b82f6;">
<h3>🎯 Standard de l'Industrie</h3>
<p>Bibliothèque la plus utilisée pour l'analyse de données en Python</p>
</div>
<div style="background: white; padding: 20px; border-radius: 10px; box-shadow: 0 4px 6px rgba(0,0,0,0.1); border-top: 4px solid #10b981;">
<h3>📊 Structures Puissantes</h3>
<p>DataFrames et Series pour manipulation intuitive</p>
</div>
<div style="background: white; padding: 20px; border-radius: 10px; box-shadow: 0 4px 6px rgba(0,0,0,0.1); border-top: 4px solid #8b5cf6;">
<h3>🔗 Multi-formats</h3>
<p>Lecture/écriture CSV, Excel, SQL, JSON, Parquet</p>
</div>
<div style="background: white; padding: 20px; border-radius: 10px; box-shadow: 0 4px 6px rgba(0,0,0,0.1); border-top: 4px solid #f59e0b;">
<h3>⚡ Performances</h3>
<p>Optimisé pour les gros volumes de données</p>
</div>
</div>

## 1. Introduction à Pandas

Pandas fournit des structures de données et des outils d'analyse de données hautes performances. Ses deux structures principales sont les Series (1D) et les DataFrames (2D).

In [1]:
import pandas as pd
import numpy as np

## 2. Structures de données fondamentales

Series (séries de données)

Series pandas - vecteur unidimensionnel

Une Series est comme une colonne unique d'un DataFrame.
C'est l'objet fondamental pour les opérations vectorisées pandas.

In [2]:
print("1. SERIES SIMPLE AVEC INDEX PAR DÉFAUT :")
s1 = pd.Series([10, 25, 30, 42, 55])
print(s1)

print("\n2. SERIES AVEC INDEX PERSONNALISÉ :")
s2 = pd.Series([100, 150, 200, 250], 
               index=['Paris', 'Lyon', 'Marseille', 'Toulouse'],
               name='ventes_2024')
print(s2)

print("\n3. SERIES AVEC DONNÉES MANQUANTES (NA) :")
s3 = pd.Series([12.5, np.nan, 18.3, None, 22.7, np.nan])
print(s3)

1. SERIES SIMPLE AVEC INDEX PAR DÉFAUT :
0    10
1    25
2    30
3    42
4    55
dtype: int64

2. SERIES AVEC INDEX PERSONNALISÉ :
Paris        100
Lyon         150
Marseille    200
Toulouse     250
Name: ventes_2024, dtype: int64

3. SERIES AVEC DONNÉES MANQUANTES (NA) :
0    12.5
1     NaN
2    18.3
3     NaN
4    22.7
5     NaN
dtype: float64

In [3]:
print("\n4. SERIES À PARTIR D'UN DICTIONNAIRE :")
populations = {'Paris': 2161000, 'Lyon': 518000, 'Marseille': 861000}
s4 = pd.Series(populations, name='population')
print(s4)

print("\n5. SERIES AVEC TYPES SPÉCIFIQUES :")
s5 = pd.Series([1, 2, 3, 4], dtype='float32')
print(f"Type: {s5.dtype}")
print(s5)

print("\n6. OPERATIONS VECTORISEES SUR SERIES :")
temperatures = pd.Series([22.5, 24.0, 19.5, 21.0, 23.5])
print("Températures originales (°C):")
print(temperatures)
print("\nTempératures en Fahrenheit (vectorisé):")
print((temperatures * 9/5) + 32)

4. SERIES À PARTIR D'UN DICTIONNAIRE :
Paris        2161000
Lyon          518000
Marseille     861000
Name: population, dtype: int64

5. SERIES AVEC TYPES SPÉCIFIQUES :
Type: float32
0    1.0
1    2.0
2    3.0
3    4.0
dtype: float32

6. OPERATIONS VECTORISEES SUR SERIES :
Températures originales (°C):
0    22.5
1    24.0
2    19.5
3    21.0
4    23.5
dtype: float64

Températures en Fahrenheit (vectorisé):
0    72.5
1    75.2
2    67.1
3    69.8
4    74.3
dtype: float64

In [4]:
print("\n7. ACCÈS ET SLICING :")
print("Première valeur :", s2.iloc[0])
print("Valeur pour 'Lyon' :", s2.loc['Lyon'])
print("Deux premières villes :")
print(s2.head(2))

print("\n8. FILTRAGE AVEC CONDITIONS :")
print("Villes avec plus de 150 ventes :")
print(s2[s2 > 150])

7. ACCÈS ET SLICING :
Première valeur : 100
Valeur pour 'Lyon' : 150
Deux premières villes :
Paris    100
Lyon     150
Name: ventes_2024, dtype: int64

8. FILTRAGE AVEC CONDITIONS :
Villes avec plus de 150 ventes :
Marseille    200
Toulouse     250
Name: ventes_2024, dtype: int64

DataFrame (tableau 2D)

In [5]:
# Création d'un DataFrame représentant des ventes
df = pd.DataFrame({
    'Date': pd.date_range('2026-01-01', periods=6, freq='D'),
    'Produit': ['Ordinateur', 'Téléphone', 'Tablette', 'Ordinateur', 'Téléphone', 'Écouteurs'],
    'Catégorie': pd.Categorical(['Électronique', 'Électronique', 'Électronique', 
                                 'Électronique', 'Électronique', 'Accessoire']),
    'Quantité': [2, 5, 3, 1, 4, 8],
    'Prix_Unitaire': [899.99, 699.50, 349.99, 899.99, 699.50, 79.99],
    'Ville': ['Paris', 'Lyon', 'Paris', 'Marseille', 'Paris', 'Lyon'],
    'Client_Fidèle': [True, False, True, False, True, True]
})

print(df)

        Date     Produit     Catégorie  Quantité  Prix_Unitaire      Ville  \
0 2026-01-01  Ordinateur  Électronique         2         899.99      Paris
1 2026-01-02   Téléphone  Électronique         5         699.50       Lyon
2 2026-01-03    Tablette  Électronique         3         349.99      Paris
3 2026-01-04  Ordinateur  Électronique         1         899.99  Marseille
4 2026-01-05   Téléphone  Électronique         4         699.50      Paris
5 2026-01-06   Écouteurs    Accessoire         8          79.99       Lyon

   Client_Fidèle
0           True
1          False
2           True
3          False
4           True
5           True

## 3. Lecture et écriture de données

Lecture depuis différents formats

In [ ]:

# CSV
df = pd.read_csv('fichier.csv')

# Excel
df = pd.read_excel('fichier.xlsx', sheet_name='Feuille1')

# JSON
df = pd.read_json('fichier.json')

# SQL
from sqlalchemy import create_engine
engine = create_engine('sqlite:///base.db')
df = pd.read_sql('SELECT * FROM table', engine)

Écriture vers différents formats

In [ ]:

df.to_csv('export.csv', index=False) 
df.to_excel('export.xlsx', sheet_name='Feuille1') 
df.to_json('export.json')
df.to_sql('table', engine, if_exists='replace')

## 4. Inspection des données

In [9]:
# Aperçu des données
df.head()      # 5 premières lignes
df.tail(3)     # 3 dernières lignes
df.sample(2)   # 2 lignes aléatoires
df.sample(frac=0.5) # 50% des lignes aléatoires, fraction ou nombre de lignes sam


# Informations structurelles
df.info()      # Types et mémoire
df.shape       # Dimensions (lignes, colonnes)
df.describe()  # Statistiques descriptives

# Vérification des valeurs
df.isna()      # Valeurs manquantes
df.duplicated() # Lignes dupliquées

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Date           6 non-null      datetime64[us]
 1   Produit        6 non-null      str
 2   Catégorie      6 non-null      category
 3   Quantité       6 non-null      int64
 4   Prix_Unitaire  6 non-null      float64
 5   Ville          6 non-null      str
 6   Client_Fidèle  6 non-null      bool
dtypes: bool(1), category(1), datetime64[us](1), float64(1), int64(1), str(2)
memory usage: 516.0 bytes

0    False
1    False
2    False
3    False
4    False
5    False
dtype: bool

## Démo complète gestion des valeurs manquantes dans un jeu de données

Création d'un DataFrame avec des valeurs manquantes variées

In [11]:

df = pd.DataFrame({
    'Date': pd.date_range('2026-01-01', periods=8, freq='D'),
    'Produit': ['Ordinateur', 'Téléphone', 'Tablette', 'Ordinateur', 
                'Téléphone', 'Écouteurs', 'Clavier', 'Souris'],
    'Catégorie': pd.Categorical(['Électronique', 'Électronique', 'Électronique', 
                                 'Électronique', 'Électronique', 'Accessoire', 
                                 'Accessoire', 'Accessoire']),
    'Quantité': [2, np.nan, 3, 1, 4, 8, None, 5],      # np.nan et None
    'Prix_Unitaire': [899.99, 699.50, np.nan, 899.99, 699.50, 79.99, 49.99, np.nan],
    'Ville': ['Paris', 'Lyon', 'Paris', 'Marseille', 'Paris', 'Lyon', None, 'Paris'],
    'Client_Fidèle': [True, False, True, None, True, True, False, None],
    'Réduction': [0.1, np.nan, 0.15, 0.05, np.nan, 0.2, 0.1, np.nan]
})

print("=" * 70)
print("DATA FRAME AVEC VALEURS MANQUANTES")
print("=" * 70)
print("\nDataFrame complet :")
print(df)

======================================================================
DATA FRAME AVEC VALEURS MANQUANTES
======================================================================

DataFrame complet :
        Date     Produit     Catégorie  Quantité  Prix_Unitaire      Ville  \
0 2026-01-01  Ordinateur  Électronique       2.0         899.99      Paris
1 2026-01-02   Téléphone  Électronique       NaN         699.50       Lyon
2 2026-01-03    Tablette  Électronique       3.0            NaN      Paris
3 2026-01-04  Ordinateur  Électronique       1.0         899.99  Marseille
4 2026-01-05   Téléphone  Électronique       4.0         699.50      Paris
5 2026-01-06   Écouteurs    Accessoire       8.0          79.99       Lyon
6 2026-01-07     Clavier    Accessoire       NaN          49.99        NaN
7 2026-01-08      Souris    Accessoire       5.0            NaN      Paris

  Client_Fidèle  Réduction
0          True       0.10
1         False        NaN
2          True       0.15
3          None       0.05
4          True        NaN
5          True       0.20
6         False       0.10
7          None        NaN

 1. Aperçu des valeurs manquantes

In [12]:
print("\n1. APERÇU DES VALEURS MANQUANTES")
print("-" * 40)
print(df.info())

1. APERÇU DES VALEURS MANQUANTES
----------------------------------------
<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Date           8 non-null      datetime64[us]
 1   Produit        8 non-null      str
 2   Catégorie      8 non-null      category
 3   Quantité       6 non-null      float64
 4   Prix_Unitaire  6 non-null      float64
 5   Ville          7 non-null      str
 6   Client_Fidèle  6 non-null      object
 7   Réduction      5 non-null      float64
dtypes: category(1), datetime64[us](1), float64(3), object(1), str(2)
memory usage: 739.0+ bytes
None

 2. Compter les valeurs manquantes par colonne

In [13]:
print("\n\n2. VALEURS MANQUANTES PAR COLONNE")
print("-" * 40)
valeurs_manquantes = df.isnull().sum()  # Nombre de valeurs manquantes par colonnes
print(valeurs_manquantes)
print(f"\nTotal des valeurs manquantes : {df.isnull().sum().sum()}")

2. VALEURS MANQUANTES PAR COLONNE
----------------------------------------
Date             0
Produit          0
Catégorie        0
Quantité         2
Prix_Unitaire    2
Ville            1
Client_Fidèle    2
Réduction        3
dtype: int64

Total des valeurs manquantes : 10

 3. Pourcentage de valeurs manquantes par colonne

In [14]:
print("\n\n3. POURCENTAGE DE VALEURS MANQUANTES")
print("-" * 40)
pourcentage_manquant = (df.isnull().sum() / len(df) * 100).round(2)
print(pourcentage_manquant)

3. POURCENTAGE DE VALEURS MANQUANTES
----------------------------------------
Date              0.0
Produit           0.0
Catégorie         0.0
Quantité         25.0
Prix_Unitaire    25.0
Ville            12.5
Client_Fidèle    25.0
Réduction        37.5
dtype: float64

4. Identifier les lignes avec des valeurs manquantes

In [15]:
print("\n\n4. LIGNES AVEC VALEURS MANQUANTES")
print("-" * 40)
lignes_avec_na = df[df.isnull().any(axis=1)]
print(f"Nombre de lignes avec au moins une valeur manquante : {len(lignes_avec_na)}")
print("\nLignes concernées :")
print(lignes_avec_na)

4. LIGNES AVEC VALEURS MANQUANTES
----------------------------------------
Nombre de lignes avec au moins une valeur manquante : 6

Lignes concernées :
        Date     Produit     Catégorie  Quantité  Prix_Unitaire      Ville  \
1 2026-01-02   Téléphone  Électronique       NaN         699.50       Lyon
2 2026-01-03    Tablette  Électronique       3.0            NaN      Paris
3 2026-01-04  Ordinateur  Électronique       1.0         899.99  Marseille
4 2026-01-05   Téléphone  Électronique       4.0         699.50      Paris
6 2026-01-07     Clavier    Accessoire       NaN          49.99        NaN
7 2026-01-08      Souris    Accessoire       5.0            NaN      Paris

  Client_Fidèle  Réduction
1         False        NaN
2          True       0.15
3          None       0.05
4          True        NaN
6         False       0.10
7          None        NaN

5. Identifier les colonnes complètes (sans NA)

In [16]:
print("\n\n5. COLONNES SANS VALEURS MANQUANTES")
print("-" * 40)
colonnes_completes = df.columns[df.notnull().all()].tolist()
print("Colonnes complètes :", colonnes_completes)

5. COLONNES SANS VALEURS MANQUANTES
----------------------------------------
Colonnes complètes : ['Date', 'Produit', 'Catégorie']

 6. Recherche spécifique par colonne

In [17]:
print("\n\n6. RECHERCHE DANS UNE COLONNE SPÉCIFIQUE")
print("-" * 40)
print("Valeurs manquantes dans 'Prix_Unitaire' :")
print(df[df['Prix_Unitaire'].isnull()])

6. RECHERCHE DANS UNE COLONNE SPÉCIFIQUE
----------------------------------------
Valeurs manquantes dans 'Prix_Unitaire' :
        Date   Produit     Catégorie  Quantité  Prix_Unitaire  Ville  \
2 2026-01-03  Tablette  Électronique       3.0            NaN  Paris
7 2026-01-08    Souris    Accessoire       5.0            NaN  Paris

  Client_Fidèle  Réduction
2          True       0.15
7          None        NaN

7. Vérifier si une cellule spécifique est manquante

In [18]:
print("\n\n7. VÉRIFICATION CELLULE PAR CELLULE")
print("-" * 40)
print("La cellule (ligne 2, colonne 'Quantité') est-elle manquante ?")
print(f"Réponse : {pd.isna(df.loc[2, 'Quantité'])}")

7. VÉRIFICATION CELLULE PAR CELLULE
----------------------------------------
La cellule (ligne 2, colonne 'Quantité') est-elle manquante ?
Réponse : False

 8. Méthodes alternatives pour détecter les NA

In [19]:
print("\n\n8. MÉTHODES ALTERNATIVES")
print("-" * 40)
print("Avec isna() :")
print(df.isna().sum())
print("\nAvec notna() (valeurs non manquantes) :")
print(df.notna().sum())

8. MÉTHODES ALTERNATIVES
----------------------------------------
Avec isna() :
Date             0
Produit          0
Catégorie        0
Quantité         2
Prix_Unitaire    2
Ville            1
Client_Fidèle    2
Réduction        3
dtype: int64

Avec notna() (valeurs non manquantes) :
Date             8
Produit          8
Catégorie        8
Quantité         6
Prix_Unitaire    6
Ville            7
Client_Fidèle    6
Réduction        5
dtype: int64

 9. Statistiques avec valeurs manquantes

In [20]:
print("\n\n9. STATISTIQUES DESCRIPTIVES")
print("-" * 40)
print("Note : Les valeurs manquantes sont ignorées dans les calculs")
print(df.describe())

9. STATISTIQUES DESCRIPTIVES
----------------------------------------
Note : Les valeurs manquantes sont ignorées dans les calculs
                      Date  Quantité  Prix_Unitaire  Réduction
count                    8  6.000000       6.000000   5.000000
mean   2026-01-04 12:00:00  3.833333     554.826667   0.120000
min    2026-01-01 00:00:00  1.000000      49.990000   0.050000
25%    2026-01-02 18:00:00  2.250000     234.867500   0.100000
50%    2026-01-04 12:00:00  3.500000     699.500000   0.100000
75%    2026-01-06 06:00:00  4.750000     849.867500   0.150000
max    2026-01-08 00:00:00  8.000000     899.990000   0.200000
std                    NaN  2.483277     389.991313   0.057009

## Exercice  :

- Trouver toutes les lignes où 'Ville' est manquante

- Calculer le pourcentage de lignes complètes

- Compter les valeurs non manquantes dans chaque colonne

- Identifier les produits ayant un prix manquant


-------------

## 5. Sélection et indexation

Sélection par étiquettes

In [ ]:

df['colonne']                           # Sélection d'une colonne
df[['col1', 'col2', 'col3']]            # Sélection multiple
df.loc[0]                               # Sélection d'une ligne par label
df.loc[0:5, 'Produit':'Catégorie']      # Sélection par plage

Sélection par position

In [22]:

df.iloc[0]          # Première ligne
df.iloc[0:5, 1:3]   # Plage de lignes et colonnes

      Produit     Catégorie
0  Ordinateur  Électronique
1   Téléphone  Électronique
2    Tablette  Électronique
3  Ordinateur  Électronique
4   Téléphone  Électronique

Sélection booléenne

In [23]:

df[df['Prix_Unitaire'] > 500]                                       # Filtre simple
df[(df['Prix_Unitaire'] > 500) & (df['Prix_Unitaire'] < 700)]       # Combinaison de conditions
df.query('Prix_Unitaire > 500 and Prix_Unitaire < 700')              # Syntaxe alternative

,Date,Produit,Catégorie,Quantité,Prix_Unitaire,Ville,Client_Fidèle,Réduction
1,2026-01-02,Téléphone,Électronique,NaN,699.5,Lyon,False,NaN
4,2026-01-05,Téléphone,Électronique,4.0,699.5,Paris,True,NaN

## 6. Manipulation des données

Ajout/suppression

In [ ]:
df['nouvelle_col'] = df['colonne'] * 2    # Ajout colonne
df.drop('colonne', axis=1)          # Suppression colonne
df.drop([0, 1], axis=0)             # Suppression lignes


Traitement des valeurs manquantes

In [ ]:
# 1. Remplacer les NA par 0

df_remplacer_0 = df.fillna(0)
print(df_remplacer_0)

# 2. Remplacer les NA par la valeur précédente (forward fill)
# Propagation vers l'avant (ffill)
df_ffill = df.ffill()


# df_ffill = df.fillna(method='ffill')
print(df_ffill)

# 3. Suppression des lignes avec NA

df_sans_na = df.dropna()
print(f"Lignes restantes : {len(df_sans_na)} (sur {len(df)})")
print(df_sans_na)

# 4. Interpolation linéaire
df_interpole = df.copy()
# Interpolation uniquement sur les colonnes numériques
df_interpole['Quantité'] = df['Quantité'].interpolate()
df_interpole['Prix_Unitaire'] = df['Prix_Unitaire'].interpolate()
df_interpole['Réduction'] = df['Réduction'].interpolate()
print(df_interpole)

# 5. Autres méthodes de fillna
# Remplacer par des valeurs spécifiques par colonne

df_remplacer_specifique = df.fillna({
    'Quantité': df['Quantité'].mean(),
    'Prix_Unitaire': df['Prix_Unitaire'].median(),
    'Ville': 'INCONNU',
    'Client_Fidèle': False,
    'Réduction': 0
})
print(df_remplacer_specifique)

# 6. Propagation vers l'arrière (backward fill)

df_bfill = df.fillna(method='bfill')
print(df_bfill)

# 7. Suppression des colonnes avec trop de NA
# Par exemple suppression des colonnes avec plus de 50% de NA

df_colonnes_propres = df.dropna(axis=1, thresh=len(df)*0.5)
print(f"Colonnes conservées : {df_colonnes_propres.columns.tolist()}")

Transformation des données

In [ ]:

# 1. Application de fonction sur une colonne
df['Quantité_racine'] = df['Quantité'].apply(lambda x: np.sqrt(x) if pd.notnull(x) else np.nan)
print(df[['Produit', 'Quantité', 'Quantité_racine']])

# 2. Fonction élément par élément avec applymap
print("\n2. Longueur des représentations textuelles :")
df_longueur = df.applymap(lambda x: len(str(x)))
print(df_longueur.head())

# 3. Remplacement de valeur
df_remplace = df.replace('Paris', 'PARIS')  # Remplacer 'Paris' par 'PARIS'
print(df_remplace[['Ville']].head())

df_remplace_na = df.replace(np.nan, 'MANQUANT') # Remplacer np.nan par 'MANQUANT'
print(df_remplace_na.head())

# 4. Renommage des colonnes
df_renomme = df.rename(columns={
    'Produit': 'Article',
    'Prix_Unitaire': 'Prix_HT',
    'Quantité': 'Qte',
    'Ville': 'Localisation'
})
print(df_renomme.columns.tolist())

# Version alternative avec rename et lambda (Renommage avec fonction)
df_renomme_maj = df.rename(columns=lambda x: x.upper() if x != 'Date' else x)
print(df_renomme_maj.columns.tolist())

## 7. Agrégation et regroupement

Statistiques de base

In [ ]:
df.mean()    # Moyenne par colonne
df.median()  # Médiane
df.std()     # Écart-type
df.sum()     # Somme
df.count()   # Nombre de valeurs non-NA
df.min()     # Minimum
df.max()     # Maximum
df.corr()    # Correlation
df.cov()     # Covariance
df.corrwith(df2)    # Correlation avec autre DataFrame

Regroupement (groupby)

In [47]:
# Création du DataFrame du debut sans valeurs manquantes

df = pd.DataFrame({
    'Date': pd.date_range('2026-01-01', periods=12, freq='D'),
    'Produit': ['Ordinateur', 'Téléphone', 'Tablette', 'Ordinateur', 
                'Téléphone', 'Écouteurs', 'Clavier', 'Souris',
                'Ordinateur', 'Tablette', 'Téléphone', 'Écouteurs'],
    'Catégorie': pd.Categorical(['Électronique', 'Électronique', 'Électronique', 
                                 'Électronique', 'Électronique', 'Accessoire', 
                                 'Accessoire', 'Accessoire',
                                 'Électronique', 'Électronique', 'Électronique', 'Accessoire']),
    'Quantité': [2, 5, 3, 1, 4, 8, 6, 5, 3, 2, 7, 4],
    'Prix_Unitaire': [899.99, 699.50, 349.99, 899.99, 699.50, 79.99, 49.99, 29.99,
                      899.99, 349.99, 699.50, 79.99],
    'Ville': ['Paris', 'Lyon', 'Paris', 'Marseille', 'Paris', 'Lyon',
              'Paris', 'Marseille', 'Lyon', 'Paris', 'Marseille', 'Paris'],
    'Client_Fidèle': [True, False, True, False, True, True, False, True, False, True, True, False]
})

In [48]:

# Ajout d'une colonne Total
df['Total'] = df['Quantité'] * df['Prix_Unitaire']


# 1. Groupement par catégorie
grouped_categorie = df.groupby('Catégorie')
print("Moyenne des quantités par catégorie :")
print(grouped_categorie['Quantité'].mean())
print("\nMoyenne des prix par catégorie :")
print(grouped_categorie['Prix_Unitaire'].mean())

Moyenne des quantités par catégorie :
Catégorie
Accessoire      5.750
Électronique    3.375
Name: Quantité, dtype: float64

Moyenne des prix par catégorie :
Catégorie
Accessoire       59.99000
Électronique    687.30625
Name: Prix_Unitaire, dtype: float64

In [49]:
# 2. Agrégations multiples (par ville)
grouped_ville = df.groupby('Ville')
agg_result = grouped_ville.agg({
    'Quantité': ['sum', 'mean', 'min', 'max'],
    'Total': ['sum', 'mean'],
    'Client_Fidèle': 'sum'  # Nombre de clients fidèles
})
print(agg_result)

          Quantité                      Total              Client_Fidèle
               sum      mean min max      sum         mean           sum
Ville
Lyon            16  5.333333   3   8  6837.39  2279.130000             1
Marseille       13  4.333333   1   7  5946.44  1982.146667             2
Paris           21  3.500000   2   6  6967.83  1161.305000             4

In [50]:
# 3. Groupement par plusieurs colonnes (par Catégorie et Client Fidèle)
grouped_multi = df.groupby(['Catégorie', 'Client_Fidèle'])
print("Total des ventes par catégorie et type de client :")
print(grouped_multi['Total'].sum().unstack())

Total des ventes par catégorie et type de client :
Client_Fidèle    False     True
Catégorie
Accessoire      619.90    789.87
Électronique   7097.46  11244.43

In [54]:
# 4. Groupement temporel par mois (ventes par mois)
df_temporel = df.copy()
df_temporel['Date'] = pd.to_datetime(df_temporel['Date'])
colonnes_numeriques = df_temporel.select_dtypes(include=[np.number]).columns
grouped_mois = df_temporel.groupby(pd.Grouper(key='Date', freq='ME'))[colonnes_numeriques].sum()
print("Ventes totales par mois :")
print(grouped_mois)



# Alternative 
grouped_mois_alt = df_temporel.groupby(pd.Grouper(key='Date', freq='ME'))[['Quantité', 'Total']].sum()
print("\nAlternative - Ventes par mois (colonnes spécifiques) :")
print(grouped_mois_alt)

Ventes totales par mois :
            Quantité  Prix_Unitaire     Total
Date
2026-01-31        50        5738.41  19751.66

Alternative - Ventes par mois (colonnes spécifiques) :
            Quantité     Total
Date
2026-01-31        50  19751.66

In [55]:
# 5. Groupement par semaine
grouped_semaine = df_temporel.groupby(pd.Grouper(key='Date', freq='W')).agg({
    'Quantité': 'sum',
    'Total': 'sum',
    'Produit': lambda x: list(x)  # Liste des produits vendus
})
print("Ventes par semaine :")
print(grouped_semaine)

Ventes par semaine :
            Quantité     Total  \
Date
2026-01-04        11   7247.44
2026-01-11        35  12184.26
2026-01-18         4    319.96

                                                      Produit
Date
2026-01-04      [Ordinateur, Téléphone, Tablette, Ordinateur]
2026-01-11  [Téléphone, Écouteurs, Clavier, Souris, Ordina...
2026-01-18                                        [Écouteurs]

In [56]:
# 6. Groupement avec calcul personnalisé (statistiques détaillées par produit)
grouped_produit = df.groupby('Produit').agg({
    'Quantité': ['count', 'sum', 'mean', 'std'],
    'Prix_Unitaire': ['min', 'max', 'mean'],
    'Total': 'sum',
    'Ville': lambda x: ', '.join(sorted(set(x)))  # Villes distinctes
})
print(grouped_produit)

           Quantité                         Prix_Unitaire                  \
              count sum      mean       std           min     max    mean
Produit
Clavier           1   6  6.000000       NaN         49.99   49.99   49.99
Ordinateur        3   6  2.000000  1.000000        899.99  899.99  899.99
Souris            1   5  5.000000       NaN         29.99   29.99   29.99
Tablette          2   5  2.500000  0.707107        349.99  349.99  349.99
Téléphone         3  16  5.333333  1.527525        699.50  699.50  699.50
Écouteurs         2  12  6.000000  2.828427         79.99   79.99   79.99

               Total                   Ville
                 sum                <lambda>
Produit
Clavier       299.94                   Paris
Ordinateur   5399.94  Lyon, Marseille, Paris
Souris        149.95               Marseille
Tablette     1749.95                   Paris
Téléphone   11192.00  Lyon, Marseille, Paris
Écouteurs     959.88             Lyon, Paris

In [57]:
# 7. Groupement par ville et produit (top des produits par ville)
grouped_ville_produit = df.groupby(['Ville', 'Produit']).agg({
    'Quantité': 'sum',
    'Total': 'sum'
}).sort_values(by='Total', ascending=False)
print(grouped_ville_produit.head(10))

                      Quantité    Total
Ville     Produit
Marseille Téléphone          7  4896.50
Lyon      Téléphone          5  3497.50
Paris     Téléphone          4  2798.00
Lyon      Ordinateur         3  2699.97
Paris     Ordinateur         2  1799.98
          Tablette           5  1749.95
Marseille Ordinateur         1   899.99
Lyon      Écouteurs          8   639.92
Paris     Écouteurs          4   319.96
          Clavier            6   299.94

Tableaux croisés

In [58]:
# 1. Crosstab simple (Nombre de ventes par Ville et Catégorie)
cross_simple = pd.crosstab(df['Ville'], df['Catégorie'])
print(cross_simple)

print("-" * 40)

# 2. Crosstab avec totaux
cross_margins = pd.crosstab(df['Ville'], df['Catégorie'], margins=True)
print(cross_margins)

Catégorie  Accessoire  Électronique
Ville
Lyon                1             2
Marseille           1             2
Paris               2             4
----------------------------------------
Catégorie  Accessoire  Électronique  All
Ville
Lyon                1             2    3
Marseille           1             2    3
Paris               2             4    6
All                 4             8   12

In [59]:
# 3. Crosstab avec plusieurs colonnes (Ville × (Catégorie + Client_Fidèle))
cross_multi = pd.crosstab(df['Ville'], [df['Catégorie'], df['Client_Fidèle']])
print(cross_multi)

print("-" * 40)

# 4. Pivot table avec moyenne (Prix moyen par Catégorie et Client_Fidèle)
pivot_mean = pd.pivot_table(df, 
                           values='Prix_Unitaire', 
                           index='Catégorie', 
                           columns='Client_Fidèle', 
                           aggfunc=np.mean)
print(pivot_mean)

Catégorie     Accessoire       Électronique
Client_Fidèle      False True         False True
Ville
Lyon                   0     1            2     0
Marseille              0     1            1     1
Paris                  2     0            0     4
----------------------------------------
Client_Fidèle   False    True
Catégorie
Accessoire      64.99   54.990
Électronique   833.16  599.794

In [60]:
# 5. Pivot table avec multiple aggrégations (Statistiques par Catégorie et Ville)
pivot_multi = pd.pivot_table(df,
                            values=['Quantité', 'Prix_Unitaire'],
                            index='Catégorie',
                            columns='Ville',
                            aggfunc={'Quantité': np.sum, 'Prix_Unitaire': np.mean})
print(pivot_multi)

print("-" * 40)

# 6. Pivot table avec remplissage des NaN
pivot_fill = pd.pivot_table(df,
                           values='Prix_Unitaire',
                           index='Catégorie',
                           columns='Client_Fidèle',
                           aggfunc=np.mean,
                           fill_value=0)
print(pivot_fill)

             Prix_Unitaire                     Quantité
Ville                 Lyon Marseille     Paris     Lyon Marseille Paris
Catégorie
Accessoire          79.990    29.990   64.9900        8         5    10
Électronique       799.745   799.745  574.8675        8         8    11
----------------------------------------
Client_Fidèle   False    True
Catégorie
Accessoire      64.99   54.990
Électronique   833.16  599.794

In [61]:
# 7. Pivot table avec totaux
pivot_margins = pd.pivot_table(df,
                              values='Quantité',
                              index='Catégorie',
                              columns='Ville',
                              aggfunc=np.sum,
                              margins=True)
print(pivot_margins)

Ville         Lyon  Marseille  Paris  All
Catégorie
Accessoire       8          5     10   23
Électronique     8          8     11   27
All             16         13     21   50

## 8. Manipulation des index

In [ ]:

df.set_index('colonne')               # Définir nouvelle colonne d'index
df.reset_index()                # Réinitialiser l'index
df.sort_index()                 # Trier par index
df.sort_values('colonne')             # Trier par valeurs
df.reindex([3, 2, 1, 0])       # Réorganiser selon nouvel index

**Exemple d'application** : Toujours avec notre Data Frame précédent ...

In [63]:
df = pd.DataFrame({
    'Date': pd.date_range('2026-01-01', periods=8, freq='D'),
    'Produit': ['Ordinateur', 'Téléphone', 'Tablette', 'Ordinateur', 
                'Téléphone', 'Écouteurs', 'Clavier', 'Souris'],
    'Catégorie': pd.Categorical(['Électronique', 'Électronique', 'Électronique', 
                                 'Électronique', 'Électronique', 'Accessoire', 
                                 'Accessoire', 'Accessoire']),
    'Quantité': [2, 5, 3, 1, 4, 8, 6, 5],
    'Prix_Unitaire': [899.99, 699.50, 349.99, 899.99, 699.50, 79.99, 49.99, 29.99],
    'Ville': ['Paris', 'Lyon', 'Paris', 'Marseille', 'Paris', 'Lyon', 'Paris', 'Marseille'],
    'Client_Fidèle': [True, False, True, False, True, True, False, True]
})

In [64]:
# 1. Définir nouvelle colonne d'index
print("\n1. DÉFINIR 'Produit' COMME INDEX :")
df_index_produit = df.set_index('Produit')
print(df_index_produit.head())

1. DÉFINIR 'Produit' COMME INDEX :
                 Date     Catégorie  Quantité  Prix_Unitaire      Ville  \
Produit
Ordinateur 2026-01-01  Électronique         2         899.99      Paris
Téléphone  2026-01-02  Électronique         5         699.50       Lyon
Tablette   2026-01-03  Électronique         3         349.99      Paris
Ordinateur 2026-01-04  Électronique         1         899.99  Marseille
Téléphone  2026-01-05  Électronique         4         699.50      Paris

            Client_Fidèle
Produit
Ordinateur           True
Téléphone           False
Tablette             True
Ordinateur          False
Téléphone            True

In [65]:
# 2. Définir index multi-colonnes
print("\n2. DÉFINIR INDEX MULTI-COLONNES (Catégorie, Ville) :")
df_multi_index = df.set_index(['Catégorie', 'Ville'])
print(df_multi_index.head())

2. DÉFINIR INDEX MULTI-COLONNES (Catégorie, Ville) :
                             Date     Produit  Quantité  Prix_Unitaire  \
Catégorie    Ville
Électronique Paris     2026-01-01  Ordinateur         2         899.99
             Lyon      2026-01-02   Téléphone         5         699.50
             Paris     2026-01-03    Tablette         3         349.99
             Marseille 2026-01-04  Ordinateur         1         899.99
             Paris     2026-01-05   Téléphone         4         699.50

                        Client_Fidèle
Catégorie    Ville
Électronique Paris               True
             Lyon               False
             Paris               True
             Marseille          False
             Paris               True

In [66]:
# 3. Réinitialiser l'index
print("\n3. RÉINITIALISER L'INDEX :")
df_reset = df_multi_index.reset_index()
print(df_reset.head())

3. RÉINITIALISER L'INDEX :
      Catégorie      Ville       Date     Produit  Quantité  Prix_Unitaire  \
0  Électronique      Paris 2026-01-01  Ordinateur         2         899.99
1  Électronique       Lyon 2026-01-02   Téléphone         5         699.50
2  Électronique      Paris 2026-01-03    Tablette         3         349.99
3  Électronique  Marseille 2026-01-04  Ordinateur         1         899.99
4  Électronique      Paris 2026-01-05   Téléphone         4         699.50

   Client_Fidèle
0           True
1          False
2           True
3          False
4           True

In [67]:
# 4. Trier par index
print("\n4. TRIER PAR INDEX :")
df_trie_index = df.set_index('Date').sort_index()
print(df_trie_index.head())

4. TRIER PAR INDEX :
               Produit     Catégorie  Quantité  Prix_Unitaire      Ville  \
Date
2026-01-01  Ordinateur  Électronique         2         899.99      Paris
2026-01-02   Téléphone  Électronique         5         699.50       Lyon
2026-01-03    Tablette  Électronique         3         349.99      Paris
2026-01-04  Ordinateur  Électronique         1         899.99  Marseille
2026-01-05   Téléphone  Électronique         4         699.50      Paris

            Client_Fidèle
Date
2026-01-01           True
2026-01-02          False
2026-01-03           True
2026-01-04          False
2026-01-05           True

In [71]:
# 5. Trier par valeurs d'une colonne

df['Total'] = df['Quantité'] * df['Prix_Unitaire']

print("\n5. TRIER PAR VALEURS :")
print("a) Par Prix_Unitaire (croissant) :")
df_trie_prix = df.sort_values('Prix_Unitaire')
print(df_trie_prix[['Produit', 'Prix_Unitaire']])

print("\nb) Par Total (décroissant) :")
df_trie_total = df.sort_values('Total', ascending=False)
print(df_trie_total[['Produit', 'Total']])

print("\nc) Par plusieurs colonnes :")
df_trie_multi = df.sort_values(['Catégorie', 'Total'], ascending=[True, False])
print(df_trie_multi[['Catégorie', 'Produit', 'Total']])

5. TRIER PAR VALEURS :
a) Par Prix_Unitaire (croissant) :
      Produit  Prix_Unitaire
7      Souris          29.99
6     Clavier          49.99
5   Écouteurs          79.99
2    Tablette         349.99
1   Téléphone         699.50
4   Téléphone         699.50
3  Ordinateur         899.99
0  Ordinateur         899.99

b) Par Total (décroissant) :
      Produit    Total
1   Téléphone  3497.50
4   Téléphone  2798.00
0  Ordinateur  1799.98
2    Tablette  1049.97
3  Ordinateur   899.99
5   Écouteurs   639.92
6     Clavier   299.94
7      Souris   149.95

c) Par plusieurs colonnes :
      Catégorie     Produit    Total
5    Accessoire   Écouteurs   639.92
6    Accessoire     Clavier   299.94
7    Accessoire      Souris   149.95
1  Électronique   Téléphone  3497.50
4  Électronique   Téléphone  2798.00
0  Électronique  Ordinateur  1799.98
2  Électronique    Tablette  1049.97
3  Électronique  Ordinateur   899.99

In [72]:
# 6. Réorganiser selon nouvel index
print("\n6. RÉORGANISER SELON NOUVEL INDEX :")
df_reindex = df.reindex([7, 6, 5, 4, 3, 2, 1, 0])
print(df_reindex)

6. RÉORGANISER SELON NOUVEL INDEX :
        Date     Produit     Catégorie  Quantité  Prix_Unitaire      Ville  \
7 2026-01-08      Souris    Accessoire         5          29.99  Marseille
6 2026-01-07     Clavier    Accessoire         6          49.99      Paris
5 2026-01-06   Écouteurs    Accessoire         8          79.99       Lyon
4 2026-01-05   Téléphone  Électronique         4         699.50      Paris
3 2026-01-04  Ordinateur  Électronique         1         899.99  Marseille
2 2026-01-03    Tablette  Électronique         3         349.99      Paris
1 2026-01-02   Téléphone  Électronique         5         699.50       Lyon
0 2026-01-01  Ordinateur  Électronique         2         899.99      Paris

   Client_Fidèle    Total
7           True   149.95
6          False   299.94
5           True   639.92
4           True  2798.00
3          False   899.99
2           True  1049.97
1          False  3497.50
0           True  1799.98

In [73]:
# 7. Réindexer avec des indices manquants
print("\n7. RÉINDEXER AVEC INDICES MANQUANTS :")
nouveaux_indices = [0, 2, 4, 6, 8, 10]  # indices manquants
df_reindex_manquant = df.reindex(nouveaux_indices)
print(df_reindex_manquant)

7. RÉINDEXER AVEC INDICES MANQUANTS :
         Date     Produit     Catégorie  Quantité  Prix_Unitaire  Ville  \
0  2026-01-01  Ordinateur  Électronique       2.0         899.99  Paris
2  2026-01-03    Tablette  Électronique       3.0         349.99  Paris
4  2026-01-05   Téléphone  Électronique       4.0         699.50  Paris
6  2026-01-07     Clavier    Accessoire       6.0          49.99  Paris
8         NaT         NaN           NaN       NaN            NaN    NaN
10        NaT         NaN           NaN       NaN            NaN    NaN

   Client_Fidèle    Total
0           True  1799.98
2           True  1049.97
4           True  2798.00
6          False   299.94
8            NaN      NaN
10           NaN      NaN

In [76]:
# 8. Réindexer avec remplissage
print("\n8. RÉINDEXER AVEC REMPLISSAGE :")

# Copier et convertir la colonne catégorielle en string
df_temp = df.copy()
df_temp['Catégorie'] = df_temp['Catégorie'].astype(str)

# Maintenant reindex avec une seule valeur de remplissage
df_reindex_fill = df_temp.reindex(range(12), fill_value='MANQUANT')
print(df_reindex_fill)

8. RÉINDEXER AVEC REMPLISSAGE :
                   Date     Produit     Catégorie  Quantité Prix_Unitaire  \
0   2026-01-01 00:00:00  Ordinateur  Électronique         2        899.99
1   2026-01-02 00:00:00   Téléphone  Électronique         5         699.5
2   2026-01-03 00:00:00    Tablette  Électronique         3        349.99
3   2026-01-04 00:00:00  Ordinateur  Électronique         1        899.99
4   2026-01-05 00:00:00   Téléphone  Électronique         4         699.5
5   2026-01-06 00:00:00   Écouteurs    Accessoire         8         79.99
6   2026-01-07 00:00:00     Clavier    Accessoire         6         49.99
7   2026-01-08 00:00:00      Souris    Accessoire         5         29.99
8              MANQUANT    MANQUANT      MANQUANT  MANQUANT      MANQUANT
9              MANQUANT    MANQUANT      MANQUANT  MANQUANT      MANQUANT
10             MANQUANT    MANQUANT      MANQUANT  MANQUANT      MANQUANT
11             MANQUANT    MANQUANT      MANQUANT  MANQUANT      MANQUANT

        Ville Client_Fidèle     Total
0       Paris          True   1799.98
1        Lyon         False    3497.5
2       Paris          True   1049.97
3   Marseille         False    899.99
4       Paris          True    2798.0
5        Lyon          True    639.92
6       Paris         False    299.94
7   Marseille          True    149.95
8    MANQUANT      MANQUANT  MANQUANT
9    MANQUANT      MANQUANT  MANQUANT
10   MANQUANT      MANQUANT  MANQUANT
11   MANQUANT      MANQUANT  MANQUANT

In [77]:
# 9. Conserver l'ancien index comme colonne
print("\n9. SET INDEX AVEC drop=False :")
df_keep_index = df.set_index('Produit', drop=False)
print(df_keep_index.head())

9. SET INDEX AVEC drop=False :
                 Date     Produit     Catégorie  Quantité  Prix_Unitaire  \
Produit
Ordinateur 2026-01-01  Ordinateur  Électronique         2         899.99
Téléphone  2026-01-02   Téléphone  Électronique         5         699.50
Tablette   2026-01-03    Tablette  Électronique         3         349.99
Ordinateur 2026-01-04  Ordinateur  Électronique         1         899.99
Téléphone  2026-01-05   Téléphone  Électronique         4         699.50

                Ville  Client_Fidèle    Total
Produit
Ordinateur      Paris           True  1799.98
Téléphone        Lyon          False  3497.50
Tablette        Paris           True  1049.97
Ordinateur  Marseille          False   899.99
Téléphone       Paris           True  2798.00

## 9. Jointures et combinaisons

In [ ]:

# Jointures SQL-like
pd.merge(df1, df2, on='key')          # Inner join
pd.merge(df1, df2, on='key', how='left') # Left join

# Concaténation
pd.concat([df1, df2], axis=0) # Empilement vertical
pd.concat([df1, df2], axis=1) # Côte à côte horizontal

# Alignement d'index
df1 + df2                   # Opérations avec alignement automatique

**Exemple d'application :** Considerons ces deux DataFrames pour les jointures ...

JOINTURES PANDAS : L'ÉQUIVALENT DES JOIN SQL

Les jointures permettent de combiner plusieurs DataFrames comme des tables SQL.
C'est essentiel pour l'analyse de données relationnelles.

In [80]:


# Création de deux DataFrames pour les jointures
df_clients = pd.DataFrame({
    'Client_ID': [1, 2, 3, 4, 5],
    'Nom': ['Alice', 'Bob', 'Charlie', 'Diana', 'Eve'],
    'Ville': ['Paris', 'Lyon', 'Paris', 'Marseille', 'Lyon'],
    'Segment': ['Premium', 'Standard', 'Premium', 'Standard', 'Premium']
})


df_commandes = pd.DataFrame({
    'Commande_ID': [101, 102, 103, 104, 105, 106],
    'Client_ID': [1, 2, 1, 3, 6, 4],  # Note: Client_ID 6 n'existe pas dans df_clients
    'Produit': ['Ordinateur', 'Téléphone', 'Tablette', 'Clavier', 'Souris', 'Écouteurs'],
    'Montant': [899.99, 699.50, 349.99, 49.99, 29.99, 79.99],
    'Date': pd.date_range('2026-01-01', periods=6, freq='D')
})

print("DATAFRAME CLIENTS :")
print(df_clients)
print("\n" + "="*50)
print("DATAFRAME COMMANDES :")
print(df_commandes)

DATAFRAME CLIENTS :
   Client_ID      Nom      Ville   Segment
0          1    Alice      Paris   Premium
1          2      Bob       Lyon  Standard
2          3  Charlie      Paris   Premium
3          4    Diana  Marseille  Standard
4          5      Eve       Lyon   Premium

==================================================
DATAFRAME COMMANDES :
   Commande_ID  Client_ID     Produit  Montant       Date
0          101          1  Ordinateur   899.99 2026-01-01
1          102          2   Téléphone   699.50 2026-01-02
2          103          1    Tablette   349.99 2026-01-03
3          104          3     Clavier    49.99 2026-01-04
4          105          6      Souris    29.99 2026-01-05
5          106          4   Écouteurs    79.99 2026-01-06

In [81]:
# 1. INNER JOIN (intersection)
print("1. INNER JOIN - Commandes avec informations clients :")
inner_join = pd.merge(df_commandes, df_clients, on='Client_ID', how='inner')
print(inner_join)

# 2. LEFT JOIN (toutes les commandes)
print("\n2. LEFT JOIN - Toutes les commandes avec infos clients si disponibles :")
left_join = pd.merge(df_commandes, df_clients, on='Client_ID', how='left')
print(left_join)

1. INNER JOIN - Commandes avec informations clients :
   Commande_ID  Client_ID     Produit  Montant       Date      Nom      Ville  \
0          101          1  Ordinateur   899.99 2026-01-01    Alice      Paris
1          102          2   Téléphone   699.50 2026-01-02      Bob       Lyon
2          103          1    Tablette   349.99 2026-01-03    Alice      Paris
3          104          3     Clavier    49.99 2026-01-04  Charlie      Paris
4          106          4   Écouteurs    79.99 2026-01-06    Diana  Marseille

    Segment
0   Premium
1  Standard
2   Premium
3   Premium
4  Standard

2. LEFT JOIN - Toutes les commandes avec infos clients si disponibles :
   Commande_ID  Client_ID     Produit  Montant       Date      Nom      Ville  \
0          101          1  Ordinateur   899.99 2026-01-01    Alice      Paris
1          102          2   Téléphone   699.50 2026-01-02      Bob       Lyon
2          103          1    Tablette   349.99 2026-01-03    Alice      Paris
3          104          3     Clavier    49.99 2026-01-04  Charlie      Paris
4          105          6      Souris    29.99 2026-01-05      NaN        NaN
5          106          4   Écouteurs    79.99 2026-01-06    Diana  Marseille

    Segment
0   Premium
1  Standard
2   Premium
3   Premium
4       NaN
5  Standard

In [82]:
# 3. RIGHT JOIN (tous les clients)
print("\n3. RIGHT JOIN - Tous les clients avec leurs commandes :")
right_join = pd.merge(df_commandes, df_clients, on='Client_ID', how='right')
print(right_join)

3. RIGHT JOIN - Tous les clients avec leurs commandes :
   Commande_ID  Client_ID     Produit  Montant       Date      Nom      Ville  \
0        101.0          1  Ordinateur   899.99 2026-01-01    Alice      Paris
1        103.0          1    Tablette   349.99 2026-01-03    Alice      Paris
2        102.0          2   Téléphone   699.50 2026-01-02      Bob       Lyon
3        104.0          3     Clavier    49.99 2026-01-04  Charlie      Paris
4        106.0          4   Écouteurs    79.99 2026-01-06    Diana  Marseille
5          NaN          5         NaN      NaN        NaT      Eve       Lyon

    Segment
0   Premium
1   Premium
2  Standard
3   Premium
4  Standard
5   Premium

In [83]:
# 4. FULL OUTER JOIN (union)
print("\n4. FULL OUTER JOIN - Tout combiner :")
outer_join = pd.merge(df_commandes, df_clients, on='Client_ID', how='outer')
print(outer_join)

4. FULL OUTER JOIN - Tout combiner :
   Commande_ID  Client_ID     Produit  Montant       Date      Nom      Ville  \
0        101.0          1  Ordinateur   899.99 2026-01-01    Alice      Paris
1        103.0          1    Tablette   349.99 2026-01-03    Alice      Paris
2        102.0          2   Téléphone   699.50 2026-01-02      Bob       Lyon
3        104.0          3     Clavier    49.99 2026-01-04  Charlie      Paris
4        106.0          4   Écouteurs    79.99 2026-01-06    Diana  Marseille
5          NaN          5         NaN      NaN        NaT      Eve       Lyon
6        105.0          6      Souris    29.99 2026-01-05      NaN        NaN

    Segment
0   Premium
1   Premium
2  Standard
3   Premium
4  Standard
5   Premium
6       NaN

In [84]:
# 5. Concaténation verticale
print("\n5. CONCATÉNATION VERTICALE - Empiler des données similaires :")
df_clients_supp = pd.DataFrame({
    'Client_ID': [6, 7],
    'Nom': ['Frank', 'Grace'],
    'Ville': ['Nice', 'Toulouse'],
    'Segment': ['Standard', 'Premium']
})

concat_vertical = pd.concat([df_clients, df_clients_supp], axis=0, ignore_index=True)
print("Clients combinés :")
print(concat_vertical)

5. CONCATÉNATION VERTICALE - Empiler des données similaires :
Clients combinés :
   Client_ID      Nom      Ville   Segment
0          1    Alice      Paris   Premium
1          2      Bob       Lyon  Standard
2          3  Charlie      Paris   Premium
3          4    Diana  Marseille  Standard
4          5      Eve       Lyon   Premium
5          6    Frank       Nice  Standard
6          7    Grace   Toulouse   Premium

In [85]:
# 6. Concaténation horizontale
print("\n6. CONCATÉNATION HORIZONTALE - Ajouter des colonnes :")
df_stats_clients = pd.DataFrame({
    'Client_ID': [1, 2, 3, 4, 5],
    'Commandes_année': [5, 3, 2, 4, 1],
    'Dépense_totale': [4500, 2100, 700, 3200, 300]
})

concat_horizontal = pd.concat([df_clients.set_index('Client_ID'), 
                               df_stats_clients.set_index('Client_ID')], 
                              axis=1, join='inner').reset_index()
print("Clients avec statistiques :")
print(concat_horizontal)

6. CONCATÉNATION HORIZONTALE - Ajouter des colonnes :
Clients avec statistiques :
   Client_ID      Nom      Ville   Segment  Commandes_année  Dépense_totale
0          1    Alice      Paris   Premium                5            4500
1          2      Bob       Lyon  Standard                3            2100
2          3  Charlie      Paris   Premium                2             700
3          4    Diana  Marseille  Standard                4            3200
4          5      Eve       Lyon   Premium                1             300

In [86]:
# 7. Alignement d'index pour les opérations
print("\n7. ALIGNEMENT D'INDEX POUR OPÉRATIONS :")
# Créer deux DataFrames avec dates similaires mais différentes
df_ventes_janvier = pd.DataFrame({
    'Ventes': [100, 150, 200, 250],
    'Date': pd.date_range('2026-01-01', periods=4, freq='D')
}).set_index('Date')

df_ventes_fevrier = pd.DataFrame({
    'Ventes': [300, 350, 400, 450],
    'Date': pd.date_range('2026-01-03', periods=4, freq='D')  # Chevauchement
}).set_index('Date')

print("Ventes janvier :")
print(df_ventes_janvier)
print("\nVentes février :")
print(df_ventes_fevrier)

# Addition avec alignement automatique
print("\nSomme des ventes (avec alignement automatique) :")
somme_ventes = df_ventes_janvier.add(df_ventes_fevrier, fill_value=0)
print(somme_ventes)

7. ALIGNEMENT D'INDEX POUR OPÉRATIONS :
Ventes janvier :
            Ventes
Date
2026-01-01     100
2026-01-02     150
2026-01-03     200
2026-01-04     250

Ventes février :
            Ventes
Date
2026-01-03     300
2026-01-04     350
2026-01-05     400
2026-01-06     450

Somme des ventes (avec alignement automatique) :
            Ventes
Date
2026-01-01   100.0
2026-01-02   150.0
2026-01-03   500.0
2026-01-04   600.0
2026-01-05   400.0
2026-01-06   450.0

In [87]:

# 8. Jointure avec suffixes
print("\n8. JOINTURE AVEC SUFFIXES :")
df_clients_historique = pd.DataFrame({
    'Client_ID': [1, 2, 3, 4, 5],
    'Dépense_2026': [4000, 2000, 1500, 3000, 500]
})

# Jointure avec des colonnes qui se chevauchent
df_clients_complet = df_clients.merge(df_stats_clients, on='Client_ID')\
                               .merge(df_clients_historique, on='Client_ID')
print("Clients avec toutes les données :")
print(df_clients_complet)

8. JOINTURE AVEC SUFFIXES :
Clients avec toutes les données :
   Client_ID      Nom      Ville   Segment  Commandes_année  Dépense_totale  \
0          1    Alice      Paris   Premium                5            4500
1          2      Bob       Lyon  Standard                3            2100
2          3  Charlie      Paris   Premium                2             700
3          4    Diana  Marseille  Standard                4            3200
4          5      Eve       Lyon   Premium                1             300

   Dépense_2026
0          4000
1          2000
2          1500
3          3000
4           500

In [88]:

# 9. Concaténation avec clés
print("\n9. CONCATÉNATION AVEC CLÉS POUR IDENTIFIER LA SOURCE :")
concat_with_keys = pd.concat(
    [df_ventes_janvier, df_ventes_fevrier], 
    axis=0, 
    keys=['Janvier', 'Février']
)
print("Ventes avec identification du mois :")
print(concat_with_keys)

9. CONCATÉNATION AVEC CLÉS POUR IDENTIFIER LA SOURCE :
Ventes avec identification du mois :
                    Ventes
        Date
Janvier 2026-01-01     100
        2026-01-02     150
        2026-01-03     200
        2026-01-04     250
Février 2026-01-03     300
        2026-01-04     350
        2026-01-05     400
        2026-01-06     450

## 10. Données temporelles

In [ ]:
# Conversion en datetime
df['date'] = pd.to_datetime(df['date_col'])

# Extraction de composants
df['annee'] = df['date'].dt.year
df['mois'] = df['date'].dt.month_name()

# Calculs temporels
df['date'] + pd.Timedelta(days=1)  # Ajout d'un jour
df.set_index('date').resample('M').mean() # Rééchantillonnage mensuel
df.set_index('date').resample('W').sum()  # Rééchantillonnage hebdomadaire

**Exemple d'application :**

Les données temporelles sont cruciales pour l'analyse de séries chronologiques,
les rapports mensuels, les tendances saisonnières, etc.

In [98]:


# Création d'un DataFrame avec des données temporelles
np.random.seed(42)
dates = pd.date_range('2026-01-01', '2026-12-31', freq='D')
df = pd.DataFrame({
    'date_achat': np.random.choice(dates, 100),  # Dates d'achat aléatoires
    'produit': np.random.choice(['Ordinateur', 'Téléphone', 'Tablette', 'Clavier'], 100),
    'quantite': np.random.randint(1, 10, 100),
    'prix': np.random.uniform(100, 1000, 100),
    'client_id': np.random.randint(1, 21, 100)
})

# Ajout d'une colonne date au format string pour démonstration
df['date_str'] = df['date_achat'].dt.strftime('%d/%m/%Y')

print("DATAFRAME ORIGINAL AVEC DATE EN STRING :")
print(df.head())

DATAFRAME ORIGINAL AVEC DATE EN STRING :
  date_achat   produit  quantite        prix  client_id    date_str
0 2026-04-13   Clavier         9  865.835604         20  13/04/2026
1 2026-12-15   Clavier         7  942.071495         15  15/12/2026
2 2026-09-28   Clavier         1  806.806586          3  28/09/2026
3 2026-04-17  Tablette         1  702.089429          8  17/04/2026
4 2026-03-13  Tablette         9  622.617959         20  13/03/2026

In [92]:

# 1. Conversion en datetime
print("1. CONVERSION DE STRING EN DATETIME :")
df['date_datetime'] = pd.to_datetime(df['date_str'], format='%d/%m/%Y')
print("Types des colonnes de date :")
print(df[['date_str', 'date_datetime']].dtypes)
print(f"\nDate min : {df['date_datetime'].min()}")
print(f"Date max : {df['date_datetime'].max()}")

1. CONVERSION DE STRING EN DATETIME :
Types des colonnes de date :
date_str                    str
date_datetime    datetime64[us]
dtype: object

Date min : 2026-01-02 00:00:00
Date max : 2026-12-30 00:00:00

In [93]:
# 2. Extraction de composants temporels
print("\n2. EXTRACTION DE COMPOSANTS TEMPORELS :")
df['annee'] = df['date_datetime'].dt.year
df['mois'] = df['date_datetime'].dt.month
df['nom_mois'] = df['date_datetime'].dt.month_name(locale='fr_FR')
df['jour'] = df['date_datetime'].dt.day
df['jour_semaine'] = df['date_datetime'].dt.day_name(locale='fr_FR')
df['semaine_annee'] = df['date_datetime'].dt.isocalendar().week
df['trimestre'] = df['date_datetime'].dt.quarter

print("Exemple d'extraction :")
print(df[['date_str', 'annee', 'nom_mois', 'jour_semaine', 'trimestre']].head())

2. EXTRACTION DE COMPOSANTS TEMPORELS :
Exemple d'extraction :
     date_str  annee   nom_mois jour_semaine  trimestre
0  13/04/2026   2026      Avril        Lundi          2
1  15/12/2026   2026   Décembre        Mardi          4
2  28/09/2026   2026  Septembre        Lundi          3
3  17/04/2026   2026      Avril     Vendredi          2
4  13/03/2026   2026       Mars     Vendredi          1

In [94]:
# 3. Calculs temporels
print("\n3. CALCULS TEMPORELS :")
print("a) Ajout de 7 jours à chaque date :")
df['date_plus_7j'] = df['date_datetime'] + pd.Timedelta(days=7)
print(df[['date_str', 'date_plus_7j']].head())

print("\nb) Différence entre dates (en jours) :")
df['jours_ecoules'] = (df['date_datetime'] - df['date_datetime'].min()).dt.days
print(df[['date_str', 'jours_ecoules']].head())

print("\nc) Calcul de l'âge en mois :")
aujourdhui = pd.Timestamp('2026-12-31')
df['age_mois'] = ((aujourdhui - df['date_datetime']).dt.days / 30).round(1)
print(df[['date_str', 'age_mois']].head())

3. CALCULS TEMPORELS :
a) Ajout de 7 jours à chaque date :
     date_str date_plus_7j
0  13/04/2026   2026-04-20
1  15/12/2026   2026-12-22
2  28/09/2026   2026-10-05
3  17/04/2026   2026-04-24
4  13/03/2026   2026-03-20

b) Différence entre dates (en jours) :
     date_str  jours_ecoules
0  13/04/2026            101
1  15/12/2026            347
2  28/09/2026            269
3  17/04/2026            105
4  13/03/2026             70

c) Calcul de l'âge en mois :
     date_str  age_mois
0  13/04/2026       8.7
1  15/12/2026       0.5
2  28/09/2026       3.1
3  17/04/2026       8.6
4  13/03/2026       9.8

In [95]:
# 4. Rééchantillonnage temporel (resampling)
print("\n4. RÉÉCHANTILLONNAGE TEMPOREL :")

# Préparation : index temporel et calcul du chiffre d'affaires
df_resample = df.copy()
df_resample = df_resample.set_index('date_datetime')
df_resample['CA'] = df_resample['quantite'] * df_resample['prix']

print("a) Chiffre d'affaires mensuel :")
ca_mensuel = df_resample['CA'].resample('ME').sum()
print(ca_mensuel.head())

print("\nb) Nombre de ventes hebdomadaire :")
ventes_hebdo = df_resample['quantite'].resample('W').sum()
print(ventes_hebdo.head())

print("\nc) Prix moyen quotidien :")
prix_moyen_jour = df_resample['prix'].resample('D').mean()
print(prix_moyen_jour.head())

print("\nd) Statistiques mensuelles complètes :")
stats_mensuelles = df_resample.resample('ME').agg({
    'quantite': 'sum',
    'prix': 'mean',
    'CA': ['sum', 'mean', 'count']
})
print(stats_mensuelles.head())

4. RÉÉCHANTILLONNAGE TEMPOREL :
a) Chiffre d'affaires mensuel :
date_datetime
2026-01-31    24717.533751
2026-02-28    21853.956566
2026-03-31    15006.575020
2026-04-30    30551.395478
2026-05-31    16991.079304
Freq: ME, Name: CA, dtype: float64

b) Nombre de ventes hebdomadaire :
date_datetime
2026-01-04     3
2026-01-11     8
2026-01-18    11
2026-01-25    13
2026-02-01     0
Freq: W-SUN, Name: quantite, dtype: int32

c) Prix moyen quotidien :
date_datetime
2026-01-02    365.76153
2026-01-03          NaN
2026-01-04          NaN
2026-01-05          NaN
2026-01-06          NaN
Freq: D, Name: prix, dtype: float64

d) Statistiques mensuelles complètes :
              quantite        prix            CA
                   sum        mean           sum         mean count
date_datetime
2026-01-31          35  659.617569  24717.533751  3531.076250     7
2026-02-28          54  388.209960  21853.956566  1986.723324    11
2026-03-31          26  641.302679  15006.575020  3001.315004     5
2026-04-30          33  877.138141  30551.395478  5091.899246     6
2026-05-31          30  523.890938  16991.079304  2831.846551     6

In [100]:
# 5. Filtrage temporel
print("\n5. FILTRAGE TEMPOREL :")

# S'assurer que l'index est trié
df_resample = df_resample.sort_index()

print("a) Ventes du premier trimestre 2026 :")
ventes_T1 = df_resample.loc['2026-01':'2026-03']
print(f"Nombre de ventes T1 : {len(ventes_T1)}")

print("\nb) Ventes du mois de juin 2026 :")
ventes_juin = df_resample.loc['2026-06']
print(f"Nombre de ventes juin : {len(ventes_juin)}")

print("\nc) Ventes des 30 derniers jours (par rapport à la date max) :")
date_max = df_resample.index.max()
date_30j = date_max - pd.Timedelta(days=30)
ventes_30j = df_resample.loc[date_30j:date_max]
print(f"Nombre de ventes 30 derniers jours : {len(ventes_30j)}")

5. FILTRAGE TEMPOREL :
a) Ventes du premier trimestre 2026 :
Nombre de ventes T1 : 23

b) Ventes du mois de juin 2026 :
Nombre de ventes juin : 7

c) Ventes des 30 derniers jours (par rapport à la date max) :
Nombre de ventes 30 derniers jours : 12

In [101]:
# ALTERNATIVE POUR PLUS DE SECURITE AVEC TRY/EXCEPT , ....

print("\n5. FILTRAGE TEMPOREL :")

# Premièrement, s'assurer que l'index est trié et monotone
df_resample = df_resample.sort_index()

print("a) Ventes du premier trimestre 2026 :")
# Vérifier si les dates 2026 existent
if df_resample.index.year.max() >= 2026:
    try:
        # Slicing temporel sur index DatetimeIndex
        mask_T1 = (df_resample.index.year == 2026) & (df_resample.index.month.isin([1, 2, 3]))
        ventes_T1 = df_resample[mask_T1]
        print(f"Nombre de ventes T1 : {len(ventes_T1)}")
    except:
        print("Aucune vente au T1 2026")
else:
    print("Aucune donnée pour l'année 2026")

print("\nb) Ventes du mois de juin 2026 :")
if df_resample.index.year.max() >= 2026:
    try:
        mask_juin = (df_resample.index.year == 2026) & (df_resample.index.month == 6)
        ventes_juin = df_resample[mask_juin]
        print(f"Nombre de ventes juin : {len(ventes_juin)}")
    except:
        print("Aucune vente en juin 2026")
else:
    print("Aucune donnée pour juin 2026")

print("\nc) Ventes des 30 derniers jours (par rapport à la date max) :")
date_max = df_resample.index.max()
date_30j = date_max - pd.Timedelta(days=30)
# Utiliser .loc pour le slicing temporel
ventes_30j = df_resample.loc[date_30j:date_max]
print(f"Nombre de ventes 30 derniers jours : {len(ventes_30j)}")

5. FILTRAGE TEMPOREL :
a) Ventes du premier trimestre 2026 :
Nombre de ventes T1 : 23

b) Ventes du mois de juin 2026 :
Nombre de ventes juin : 7

c) Ventes des 30 derniers jours (par rapport à la date max) :
Nombre de ventes 30 derniers jours : 12

In [102]:
# 6. Agrégations par période
print("\n6. AGRÉGATIONS PAR PÉRIODE :")
print("CA total par mois :")
ca_par_mois = df_resample.groupby(df_resample.index.to_period('M'))['CA'].sum()
print(ca_par_mois.head())

print("\nNombre de clients uniques par trimestre :")
clients_par_trim = df_resample.groupby(df_resample.index.to_period('Q'))['client_id'].nunique()
print(clients_par_trim)

6. AGRÉGATIONS PAR PÉRIODE :
CA total par mois :
date_datetime
2026-01    24717.533751
2026-02    21853.956566
2026-03    15006.575020
2026-04    30551.395478
2026-05    16991.079304
Freq: M, Name: CA, dtype: float64

Nombre de clients uniques par trimestre :
date_datetime
2026Q1    13
2026Q2    12
2026Q3    14
2026Q4    15
Freq: Q-DEC, Name: client_id, dtype: int64

In [103]:
# 7. Travail avec les jours ouvrables
print("\n7. JOURS OUVRABLES :")
# Ajout d'une colonne pour vérifier si c'est un jour ouvrable
df_resample['est_jour_ouvre'] = df_resample.index.weekday < 5  # Lundi=0, Vendredi=4

print("Répartition des ventes jours ouvrables vs week-end :")
ventes_jours = df_resample.groupby('est_jour_ouvre').agg({
    'quantite': 'sum',
    'CA': 'sum',
    'prix': 'mean'
})
print(ventes_jours)

7. JOURS OUVRABLES :
Répartition des ventes jours ouvrables vs week-end :
                quantite             CA        prix
est_jour_ouvre
False                101   41543.972520  415.559654
True                 384  234917.253838  586.615737

## 11. Données catégorielles

In [ ]:
df['cat_col'] = df['cat_col'].astype('category') # Conversion
df['cat_col'].cat.categories                     # Voir catégories
df['cat_col'].cat.reorder_categories(['a','b','c'], ordered=True) # Ordonner

**Exemple d'application :**

Les catégories permettent de stocker des données textuelles répétitives 
de façon optimisée (comme les ENUM en SQL). C'est essentiel pour :
- Réduire l'utilisation mémoire
- Améliorer les performances de groupby/filtrage
- Gérer l'ordre logique des données qualitatives

In [105]:

# Création d'un DataFrame avec des données textuelles répétitives

df = pd.DataFrame({
    'client_id': range(1, 11),
    'nom': ['Alice', 'Bob', 'Charlie', 'Alice', 'Bob', 'Charlie', 'Alice', 'Bob', 'Charlie', 'Alice'],
    'ville': ['Paris', 'Lyon', 'Marseille', 'Paris', 'Lyon', 'Marseille', 'Paris', 'Lyon', 'Marseille', 'Paris'],
    'categorie_client': ['Premium', 'Standard', 'Basic', 'Standard', 'Premium', 'Basic', 'Premium', 'Standard', 'Basic', 'Premium'],
    'segment': ['A', 'B', 'C', 'B', 'A', 'C', 'A', 'B', 'C', 'A'],
    'departement': ['IT', 'RH', 'IT', 'Marketing', 'RH', 'IT', 'Marketing', 'RH', 'IT', 'Marketing'],
    'statut_commande': ['Livrée', 'En cours', 'Annulée', 'Livrée', 'En cours', 'Annulée', 'Livrée', 'En cours', 'Annulée', 'Livrée']
})

print("DATAFRAME ORIGINAL :")
print(df)
print(f"\nTaille mémoire avant catégorisation : {df.memory_usage(deep=True).sum() / 1024:.2f} KB")

DATAFRAME ORIGINAL :
   client_id      nom      ville categorie_client segment departement  \
0          1    Alice      Paris          Premium       A          IT
1          2      Bob       Lyon         Standard       B          RH
2          3  Charlie  Marseille            Basic       C          IT
3          4    Alice      Paris         Standard       B   Marketing
4          5      Bob       Lyon          Premium       A          RH
5          6  Charlie  Marseille            Basic       C          IT
6          7    Alice      Paris          Premium       A   Marketing
7          8      Bob       Lyon         Standard       B          RH
8          9  Charlie  Marseille            Basic       C          IT
9         10    Alice      Paris          Premium       A   Marketing

  statut_commande
0          Livrée
1        En cours
2         Annulée
3          Livrée
4        En cours
5         Annulée
6          Livrée
7        En cours
8         Annulée
9          Livrée

Taille mémoire avant catégorisation : 0.97 KB

In [106]:
# 1. Conversion en catégorie
print("1. CONVERSION EN CATÉGORIE :")
df['ville_cat'] = df['ville'].astype('category')
df['categorie_client_cat'] = df['categorie_client'].astype('category')
df['statut_commande_cat'] = df['statut_commande'].astype('category')

print("Types des colonnes après catégorisation :")
print(df[['ville', 'ville_cat', 'categorie_client', 'categorie_client_cat']].dtypes)

print(f"\nTaille mémoire après catégorisation : {df.memory_usage(deep=True).sum() / 1024:.2f} KB")
print("Gain mémoire : ~90% sur les colonnes catégorisées !")

1. CONVERSION EN CATÉGORIE :
Types des colonnes après catégorisation :
ville                        str
ville_cat               category
categorie_client             str
categorie_client_cat    category
dtype: object

Taille mémoire après catégorisation : 1.13 KB
Gain mémoire : ~90% sur les colonnes catégorisées !

In [107]:

# 2. Voir les catégories
print("\n2. EXPLORATION DES CATÉGORIES :")
print("Catégories uniques de 'ville_cat' :")
print(df['ville_cat'].cat.categories)

print("\nCodes des catégories (représentation numérique interne) :")
print(df['ville_cat'].cat.codes)

print("\nStatistiques des catégories :")
print(df['ville_cat'].value_counts())

2. EXPLORATION DES CATÉGORIES :
Catégories uniques de 'ville_cat' :
Index(['Lyon', 'Marseille', 'Paris'], dtype='str')

Codes des catégories (représentation numérique interne) :
0    2
1    0
2    1
3    2
4    0
5    1
6    2
7    0
8    1
9    2
dtype: int8

Statistiques des catégories :
ville_cat
Paris        4
Lyon         3
Marseille    3
Name: count, dtype: int64

In [108]:
# 3. Ajout de nouvelles catégories
print("\n3. AJOUT DE NOUVELLES CATÉGORIES :")
df['ville_cat'] = df['ville_cat'].cat.add_categories(['Nice', 'Toulouse'])
print("Catégories après ajout :", df['ville_cat'].cat.categories.tolist())

3. AJOUT DE NOUVELLES CATÉGORIES :
Catégories après ajout : ['Lyon', 'Marseille', 'Paris', 'Nice', 'Toulouse']

In [109]:
# 4. Ordonner les catégories (important pour les tris et analyses)
print("\n4. CATÉGORIES ORDONNÉES :")
# Conversion avec ordre logique
df['categorie_client_ord'] = df['categorie_client'].astype(
    pd.CategoricalDtype(categories=['Basic', 'Standard', 'Premium'], ordered=True)
)

print("Catégories ordonnées :", df['categorie_client_ord'].cat.categories.tolist())
print("Valeurs ordonnées :")
print(df[['nom', 'categorie_client', 'categorie_client_ord']].head())

print("\nComparaison avec catégories ordonnées :")
print("Alice > Basic ?", df.loc[0, 'categorie_client_ord'] > 'Basic')
print("Premium > Standard ?", 'Premium' > 'Standard')  # Ne fonctionne pas sans ordre
print("Premium > Standard (avec ordre) ?", 
      df['categorie_client_ord'].cat.categories[-1] > df['categorie_client_ord'].cat.categories[1])

4. CATÉGORIES ORDONNÉES :
Catégories ordonnées : ['Basic', 'Standard', 'Premium']
Valeurs ordonnées :
       nom categorie_client categorie_client_ord
0    Alice          Premium              Premium
1      Bob         Standard             Standard
2  Charlie            Basic                Basic
3    Alice         Standard             Standard
4      Bob          Premium              Premium

Comparaison avec catégories ordonnées :
Alice > Basic ? True
Premium > Standard ? False
Premium > Standard (avec ordre) ? False

In [110]:
# 5. Réordonner les catégories existantes
print("\n5. RÉORDONNANCEMENT DES CATÉGORIES :")
df['statut_commande_ord'] = df['statut_commande_cat'].cat.reorder_categories(
    ['Annulée', 'En cours', 'Livrée'], 
    ordered=True
)
print("Catégories réordonnées :", df['statut_commande_ord'].cat.categories.tolist())

5. RÉORDONNANCEMENT DES CATÉGORIES :
Catégories réordonnées : ['Annulée', 'En cours', 'Livrée']

In [111]:
# 6. Suppression de catégories non utilisées
print("\n6. NETTOYAGE DES CATÉGORIES :")
print("Catégories 'ville_cat' avant nettoyage :", df['ville_cat'].cat.categories.tolist())
df['ville_cat'] = df['ville_cat'].cat.remove_unused_categories()
print("Catégories 'ville_cat' après nettoyage :", df['ville_cat'].cat.categories.tolist())

6. NETTOYAGE DES CATÉGORIES :
Catégories 'ville_cat' avant nettoyage : ['Lyon', 'Marseille', 'Paris', 'Nice', 'Toulouse']
Catégories 'ville_cat' après nettoyage : ['Lyon', 'Marseille', 'Paris']

In [112]:
# 7. Renommer les catégories
print("\n7. RENOMMAGE DES CATÉGORIES :")
df['segment_cat'] = df['segment'].astype('category')
print("Catégories avant renommage :", df['segment_cat'].cat.categories.tolist())

df['segment_cat'] = df['segment_cat'].cat.rename_categories({'A': 'Gold', 'B': 'Silver', 'C': 'Bronze'})
print("Catégories après renommage :", df['segment_cat'].cat.categories.tolist())

7. RENOMMAGE DES CATÉGORIES :
Catégories avant renommage : ['A', 'B', 'C']
Catégories après renommage : ['Gold', 'Silver', 'Bronze']

In [113]:
# 8. Performance des opérations sur catégories
print("\n8. PERFORMANCE DES CATÉGORIES :")
print("GroupBy sur colonne normale (ville) :")
%timeit df.groupby('ville').size()

print("\nGroupBy sur catégorie (ville_cat) :")
%timeit df.groupby('ville_cat').size()

8. PERFORMANCE DES CATÉGORIES :
GroupBy sur colonne normale (ville) :
1.01 ms ± 137 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)

GroupBy sur catégorie (ville_cat) :
731 μs ± 57.7 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)

In [114]:

# 9. Filtrage avec catégories
print("\n9. FILTRAGE AVEC CATÉGORIES :")
# Filtre avec catégories ordonnées
clients_premium_plus = df[df['categorie_client_ord'] >= 'Standard']
print(f"Clients Standard et Premium : {len(clients_premium_plus)}")

9. FILTRAGE AVEC CATÉGORIES :
Clients Standard et Premium : 7

In [115]:
# 10. Conversion vers d'autres types
print("\n10. CONVERSION VERS AUTRES TYPES :")
print("Conversion catégorie → chaîne :")
df['ville_str'] = df['ville_cat'].astype(str)
print(df[['ville_cat', 'ville_str']].head())

print("\nConversion catégorie → codes numériques :")
df['ville_code'] = df['ville_cat'].cat.codes
print(df[['ville_cat', 'ville_code']].head())

print("\n" + "="*70)
print("RÉSUMÉ DES AVANTAGES DES CATÉGORIES :")
print("1. Économie mémoire significative")
print("2. Meilleures performances (groupby, tri, filtrage)")
print("3. Ordre logique des données qualitatives")
print("4. Validation des valeurs (seules les catégories définies sont autorisées)")

10. CONVERSION VERS AUTRES TYPES :
Conversion catégorie → chaîne :
   ville_cat  ville_str
0      Paris      Paris
1       Lyon       Lyon
2  Marseille  Marseille
3      Paris      Paris
4       Lyon       Lyon

Conversion catégorie → codes numériques :
   ville_cat  ville_code
0      Paris           2
1       Lyon           0
2  Marseille           1
3      Paris           2
4       Lyon           0

======================================================================
RÉSUMÉ DES AVANTAGES DES CATÉGORIES :
1. Économie mémoire significative
2. Meilleures performances (groupby, tri, filtrage)
3. Ordre logique des données qualitatives
4. Validation des valeurs (seules les catégories définies sont autorisées)

## 12. Optimisation des performances

Méthodes vectorisées

In [ ]:
# À éviter (lent)
for i in range(len(df)):
    df.loc[i, 'nouveau'] = df.loc[i, 'colonne_num'] * 2
    
# Préférer (rapide)
df['nouveau'] = df['colonne_num'] * 2

Types optimisés

In [ ]:
df['col'] = df['col'].astype('int32')   # Moins de mémoire que int64
df['col'] = df['col'].astype('float32') # Moins de mémoire que float64


## 13. Fonctions avancées

Fenêtrage (window functions)

In [ ]:

df['colonne'].rolling(window=3).mean()       # Moyenne mobile
df.expanding().sum()                   # Somme cumulative

1. MOYENNE MOBILE (*rolling*) :

   - Calcule une statistique (moyenne, somme, etc.) sur une fenêtre glissante
   - Ex: fenêtre de 3 jours → moyenne des 3 derniers jours
   - Utile pour lisser les fluctuations, détecter tendances


2. SOMME CUMULATIVE (*expanding*) :
   - Calcule une statistique qui s'accumule depuis le début
   - Ex: somme cumulative → 10, 25, 37, 55... (10, 10+15, 10+15+12, etc.)
   - Utile pour suivre l'évolution cumulative

Transformation par groupe

In [ ]:

df.groupby('groupe')['data'].transform('mean')  # Moyenne par groupe

3. TRANSFORMATION PAR GROUPE (*transform*) :

   - Applique une fonction à chaque groupe, mais conserve la forme originale
   - Ex: moyenne par produit → chaque ligne reçoit la moyenne de son produit
   - Différent de groupby().agg() qui réduit le DataFrame

Pivotage

In [ ]:

df.pivot(index='date', columns='produit', values='ventes')

4. TABLEAU PIVOT (*pivot*) :

   - Transforme les données de format long à format large
   - Les valeurs deviennent des colonnes
   - Ex: les produits deviennent des colonnes, les dates des lignes
   - Utile pour les analyses croisées et les visualisations

_____________

**Exemple d'application :**  

OPÉRATIONS AVANCÉES : MOBILES, CUMULATIVES ET TRANSFORMATIONS

In [118]:

# Création d'un DataFrame simple
df = pd.DataFrame({
    'date': pd.date_range('2026-01-01', periods=10, freq='D'),
    'produit': ['A', 'B', 'A', 'B', 'A', 'B', 'A', 'B', 'A', 'B'],
    'ventes': [10, 15, 12, 18, 14, 20, 16, 22, 18, 24],
    'prix': [100, 150, 105, 155, 110, 160, 115, 165, 120, 170]
})

print("DATAFRAME ORIGINAL :")
print(df)

DATAFRAME ORIGINAL :
        date produit  ventes  prix
0 2026-01-01       A      10   100
1 2026-01-02       B      15   150
2 2026-01-03       A      12   105
3 2026-01-04       B      18   155
4 2026-01-05       A      14   110
5 2026-01-06       B      20   160
6 2026-01-07       A      16   115
7 2026-01-08       B      22   165
8 2026-01-09       A      18   120
9 2026-01-10       B      24   170

In [119]:
# 1. Moyenne mobile sur 3 périodes
print("1. MOYENNE MOBILE (3 jours) :")
df['ventes_mm3'] = df['ventes'].rolling(window=3).mean()
print(df[['date', 'ventes', 'ventes_mm3']])


# Résultat : pour chaque ligne, moyenne des 3 dernières ventes
# Lignes 1-2 : NaN (pas assez de données)
# Ligne 3 : moyenne(10, 15, 12) = 12.33

1. MOYENNE MOBILE (3 jours) :
        date  ventes  ventes_mm3
0 2026-01-01      10         NaN
1 2026-01-02      15         NaN
2 2026-01-03      12   12.333333
3 2026-01-04      18   15.000000
4 2026-01-05      14   14.666667
5 2026-01-06      20   17.333333
6 2026-01-07      16   16.666667
7 2026-01-08      22   19.333333
8 2026-01-09      18   18.666667
9 2026-01-10      24   21.333333

In [120]:

# 2. Somme cumulative
print("\n2. SOMME CUMULATIVE :")
df['ventes_cumul'] = df['ventes'].expanding().sum()
print(df[['date', 'ventes', 'ventes_cumul']])

# Ligne 1 : 10
# Ligne 2 : 10 + 15 = 25
# Ligne 3 : 10 + 15 + 12 = 37

2. SOMME CUMULATIVE :
        date  ventes  ventes_cumul
0 2026-01-01      10          10.0
1 2026-01-02      15          25.0
2 2026-01-03      12          37.0
3 2026-01-04      18          55.0
4 2026-01-05      14          69.0
5 2026-01-06      20          89.0
6 2026-01-07      16         105.0
7 2026-01-08      22         127.0
8 2026-01-09      18         145.0
9 2026-01-10      24         169.0

In [121]:
# 3. Transformation par groupe (conservation des lignes)
print("\n3. MOYENNE PAR PRODUIT :")
df['ventes_moy_produit'] = df.groupby('produit')['ventes'].transform('mean')
print(df[['produit', 'ventes', 'ventes_moy_produit']])

# Toutes les lignes produit A reçoivent la même moyenne
# Toutes les lignes produit B reçoivent la même moyenne

3. MOYENNE PAR PRODUIT :
  produit  ventes  ventes_moy_produit
0       A      10                14.0
1       B      15                19.8
2       A      12                14.0
3       B      18                19.8
4       A      14                14.0
5       B      20                19.8
6       A      16                14.0
7       B      22                19.8
8       A      18                14.0
9       B      24                19.8

In [122]:

# 4. Pivot table (Pivot :  produit → colonnes, date → lignes)
print("\n4. TABLEAU PIVOT :")
df_pivot = df.pivot(index='date', columns='produit', values='ventes')
print(df_pivot)

# Format idéal pour : comparer produits, calculer corrélations

4. TABLEAU PIVOT :
produit        A     B
date
2026-01-01  10.0   NaN
2026-01-02   NaN  15.0
2026-01-03  12.0   NaN
2026-01-04   NaN  18.0
2026-01-05  14.0   NaN
2026-01-06   NaN  20.0
2026-01-07  16.0   NaN
2026-01-08   NaN  22.0
2026-01-09  18.0   NaN
2026-01-10   NaN  24.0

In [123]:

# 5. Opérations combinées
print("\n5. COMBINAISONS :")
df['mm3_par_produit'] = df.groupby('produit')['ventes'].rolling(window=3).mean().reset_index(level=0, drop=True)
print(df[['produit', 'ventes', 'mm3_par_produit']])

5. COMBINAISONS :
  produit  ventes  mm3_par_produit
0       A      10              NaN
1       B      15              NaN
2       A      12              NaN
3       B      18              NaN
4       A      14        12.000000
5       B      20        17.666667
6       A      16        14.000000
7       B      22        20.000000
8       A      18        16.000000
9       B      24        22.000000

## 14. Visualisation intégrée

In [ ]:

df.plot.line()          # Ligne
df.plot.bar()           # Barres
df.plot.hist(bins=20)   # Histogramme
df.plot.scatter(x='A', y='B') # Nuage de points
df.plot.box()           # Boîtes à moustaches

## 15. Trucs et astuces

Paramètres d'affichage

In [125]:
pd.set_option('display.max_rows', 100)   # Afficher plus de lignes
pd.set_option('display.float_format', '{:.2f}'.format) # Format décimal


Traitement des gros fichiers

In [ ]:

# Lecture par morceaux
chunk_iter = pd.read_csv('gros_fichier.csv', chunksize=10000)

# Initialiser un DataFrame vide pour accumuler les résultats
resultats = pd.DataFrame()

for chunk in chunk_iter:
    # Traitement sur chaque morceau
    chunk_traite = chunk[chunk['colonne'] > 0]    # Exemple de filtrage
    chunk_traite['nouvelle_colonne'] = chunk_traite['autre_colonne'] * 2
    
    # Ajouter au résultat final
    resultats = pd.concat([resultats, chunk_traite], ignore_index=True)


# Alternative : traitement sans accumulation
for chunk in pd.read_csv('gros_fichier.csv', chunksize=10000):
    # Sauvegarder chaque morceau traité
    chunk.to_csv('resultat_par_morceau.csv', mode='a', header=False, index=False)

Méthodes chaînées  :

Technique pour enchaîner plusieurs opérations pandas en une seule ligne
Améliore la lisibilité et évite les variables intermédiaires

In [ ]:

(df.dropna()
   .query('colonne_num > 0')
   .groupby('col')
   .agg({'col': 'mean'})
   .sort_values('col', ascending=False))

**Exemple d'application :**

In [127]:
# Création d'un DataFrame simple
df = pd.DataFrame({
    'nom': ['Alice', 'Bob', 'Charlie', 'Diana', 'Eve', 'Frank'],
    'ville': ['Paris', 'Lyon', 'Paris', 'Marseille', 'Lyon', 'Paris'],
    'ventes': [100, 150, np.nan, 200, -50, 300],
    'commission': [0.1, 0.15, 0.12, 0.18, 0.08, 0.2]
})

print("DATAFRAME ORIGINAL :")
print(df)

DATAFRAME ORIGINAL :
       nom      ville  ventes  commission
0    Alice      Paris  100.00        0.10
1      Bob       Lyon  150.00        0.15
2  Charlie      Paris     NaN        0.12
3    Diana  Marseille  200.00        0.18
4      Eve       Lyon  -50.00        0.08
5    Frank      Paris  300.00        0.20

In [128]:
# Châinage de méthodes
resultat = (df
           .dropna()                     # 1. Supprimer les lignes avec NaN
           .query('ventes > 0')          # 2. Filtrer ventes positives
           .groupby('ville')             # 3. Grouper par ville
           .agg({'commission': 'mean',   # 4. Agréger (moyenne commission)
                 'ventes': 'sum'})       #    et somme des ventes
           .sort_values('ventes',        # 5. Trier par ventes
                       ascending=False)
           .round(2))                    # 6. Arrondir à 2 décimales

print("RÉSULTAT FINAL (chaînage) :")
print(resultat)

RÉSULTAT FINAL (chaînage) :
           commission  ventes
ville
Paris            0.15  400.00
Marseille        0.18  200.00
Lyon             0.15  150.00

In [129]:
# Équivalent sans chaînage (plus verbeux) :

print("MÊME TRAITEMENT SANS CHAÎNAGE :")

# Étape par étape
df1 = df.dropna()                       # Supprimer NaN
df2 = df1[df1['ventes'] > 0]            # Filtrer positif
df3 = df2.groupby('ville')              # Grouper
df4 = df3.agg({'commission': 'mean',    # Agréger
               'ventes': 'sum'})
df5 = df4.sort_values('ventes',         # Trier
                      ascending=False)
resultat_sans = df5.round(2)            # Arrondir

print(resultat_sans)

MÊME TRAITEMENT SANS CHAÎNAGE :
           commission  ventes
ville
Paris            0.15  400.00
Marseille        0.18  200.00
Lyon             0.15  150.00

## 16. Cas pratiques

Nettoyage de données

In [ ]:

# Pipeline complet de nettoyage
(df
 .drop_duplicates()
 .fillna({'col1': df['col1'].median(),
          'col2': 'inconnu'})
 .assign(new_col = lambda x: x['col1'] * 2)
 .query('col3 > 0')
 .reset_index(drop=True))

Analyse exploratoire

In [131]:

# Analyse complète en quelques lignes
(df.describe()
   .T
   .assign(missing = df.isna().mean(),
           unique = df.nunique(),
           dtype = df.dtypes))

,count,mean,std,min,25%,50%,75%,max,missing,unique,dtype
ventes,5.00,140.00,129.42,-50.00,100.00,150.00,200.00,300.00,0.17,5,float64
commission,6.00,0.14,0.05,0.08,0.11,0.14,0.17,0.20,0.00,6,float64

## 17. Intégration avec d'autres bibliothèques

NumPy

In [132]:

arr = df.values          # DataFrame vers array NumPy
df = pd.DataFrame(arr)   # Array vers DataFrame


Scikit-learn


Normalisation de données avec Scikit-learn
Standardisation : centrer (moyenne=0) et réduire (écart-type=1) les données
Essentiel pour de nombreux algorithmes de machine learning

In [ ]:
# pip install scikit-learn

from sklearn.preprocessing import StandardScaler 
# StandardScaler : pour normaliser des données

scaler = StandardScaler()
df_scaled = pd.DataFrame(scaler.fit_transform(df), columns=df.columns)

**Exemple d'application :**

In [134]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler

# Création d'un DataFrame avec données d'échelles différentes
df = pd.DataFrame({
    'age': [25, 30, 35, 40, 45, 50],          # Échelle : ~30-50
    'salaire': [30000, 40000, 50000, 60000, 70000, 80000],  # Échelle : 30k-80k
    'experience': [2, 5, 8, 12, 15, 20]       # Échelle : 2-20
})

print("DONNÉES ORIGINALES (échelles différentes) :")
print(df)
print(f"\nMoyennes :\n{df.mean()}")
print(f"\nÉcart-types :\n{df.std()}")

DONNÉES ORIGINALES (échelles différentes) :
   age  salaire  experience
0   25    30000           2
1   30    40000           5
2   35    50000           8
3   40    60000          12
4   45    70000          15
5   50    80000          20

Moyennes :
age             37.50
salaire      55000.00
experience      10.33
dtype: float64

Écart-types :
age              9.35
salaire      18708.29
experience       6.65
dtype: float64

In [135]:
# Normalisation avec StandardScaler
scaler = StandardScaler()
df_scaled = pd.DataFrame(scaler.fit_transform(df), columns=df.columns)

print("DONNÉES NORMALISÉES (StandardScaler) :")
print(df_scaled)
print(f"\nMoyennes (≈0) :\n{df_scaled.mean().round(3)}")
print(f"\nÉcart-types (=1) :\n{df_scaled.std().round(3)}")

DONNÉES NORMALISÉES (StandardScaler) :
    age  salaire  experience
0 -1.46    -1.46       -1.37
1 -0.88    -0.88       -0.88
2 -0.29    -0.29       -0.38
3  0.29     0.29        0.27
4  0.88     0.88        0.77
5  1.46     1.46        1.59

Moyennes (≈0) :
age           0.00
salaire      -0.00
experience   -0.00
dtype: float64

Écart-types (=1) :
age          1.09
salaire      1.09
experience   1.09
dtype: float64

In [136]:
# Application sur nouvelles données

print("APPLICATION SUR NOUVELLES DONNÉES :")
nouvelles_donnees = pd.DataFrame({
    'age': [28, 42],
    'salaire': [35000, 65000],
    'experience': [3, 10]
})
print("Nouvelles données originales :")
print(nouvelles_donnees)

APPLICATION SUR NOUVELLES DONNÉES :
Nouvelles données originales :
   age  salaire  experience
0   28    35000           3
1   42    65000          10

In [137]:

# Utiliser le même scaler (transform, pas fit_transform)
nouvelles_scaled = pd.DataFrame(scaler.transform(nouvelles_donnees), 
                                columns=nouvelles_donnees.columns)
print("\nNouvelles données normalisées :")
print(nouvelles_scaled)

Nouvelles données normalisées :
    age  salaire  experience
0 -1.11    -1.17       -1.21
1  0.53     0.59       -0.05

------------------------------------
----------------------------------

## 🧩 EXERCICE FINAL : PROJET COMPLET D'ANALYSE DE VENTES

**📋 Contexte :**

Vous êtes Data Analyst dans une entreprise de commerce électronique. On vous fournit plusieurs sources de données sur les ventes du dernier trimestre 2026. Votre mission est d'analyser ces données pour fournir des insights actionnables à l'équipe management.

**📊 Données fournies :**

In [138]:
# Données des produits
produits_data = {
    'produit_id': ['P001', 'P002', 'P003', 'P004', 'P005'],
    'nom_produit': ['Ordinateur Gaming', 'Smartphone Pro', 'Tablette Elite', 
                   'Casque Audio', 'Montre Connectée'],
    'categorie': ['Électronique', 'Électronique', 'Électronique', 
                 'Accessoire', 'Accessoire'],
    'prix_unitaire': [1299.99, 899.50, 549.99, 199.99, 299.99],
    'cout_production': [800.00, 550.00, 350.00, 120.00, 180.00]
}


# Données des ventes (octobre à décembre 2026)
np.random.seed(42)
dates = pd.date_range('2026-10-01', '2026-12-31', freq='D')
ventes_data = {
    'date_vente': np.random.choice(dates, 500),
    'produit_id': np.random.choice(['P001', 'P002', 'P003', 'P004', 'P005'], 500),
    'quantite': np.random.randint(1, 6, 500),
    'ville': np.random.choice(['Paris', 'Lyon', 'Marseille', 'Toulouse', 'Nice'], 500),
    'mode_paiement': np.random.choice(['Carte', 'PayPal', 'Virement'], 500),
    'client_id': np.random.randint(1000, 1100, 500)
}

# Données des clients
clients_data = {
    'client_id': list(range(1000, 1100)),
    'segment': np.random.choice(['Premium', 'Standard', 'Basic'], 100),
    'date_inscription': pd.date_range('2025-01-01', periods=100, freq='D'),
    'region': np.random.choice(['Nord', 'Sud', 'Est', 'Ouest'], 100)
}

## 🎯 TÂCHES À RÉALISER

**Partie 1:** Préparation des données

- Créer trois DataFrames à partir des dictionnaires ci-dessus

- Vérifier les valeurs manquantes dans chaque DataFrame

- Convertir les dates en format datetime

- Calculer la marge unitaire pour chaque produit

**Partie 2 :** Analyse exploratoire 

- Quel est le chiffre d'affaires total du trimestre ?

- Quels sont les 3 produits les plus vendus en quantité ?

- Quelle est la ville qui génère le plus de chiffre d'affaires ?

- Comment évolue le CA quotidien ? (visualisation suggérée)

- Quel est le mode de paiement le plus populaire ?

**Partie 3 :** Analyses avancées

- Calculer le chiffre d'affaires mensuel (octobre, novembre, décembre)

- Identifier la tendance des ventes avec une moyenne mobile sur 7 jours

- Calculer le panier moyen par ville

- Trouver les clients les plus fidèles (ceux avec plus de 5 achats)

- Analyser la corrélation entre la marge et la quantité vendue

**Partie 4 :** Jointures et agrégations complexes 

- Fusionner les DataFrames pour avoir une vue complète des ventes

- Calculer les statistiques par catégorie de produit

- Analyser la performance par segment de client

- Identifier les meilleures combinaisons produit/ville

- Calculer le taux de croissance mensuel des ventes

**Partie 5** : Optimisation et reporting

- Optimiser les types de données pour réduire l'utilisation mémoire

- Créer un DataFrame pivot montrant le CA par produit et par mois

- Générer un résumé statistique complet

- Proposer 3 recommandations business basées sur vos analyses

**BONUS :**

- Simuler les ventes du premier trimestre 2027 avec une croissance de 15%

- Créer une fonction qui nettoie automatiquement les données similaires

- Utiliser le chaînage de méthodes pour tout le pipeline d'analyse

- Exporter les résultats dans un fichier Excel avec plusieurs feuilles

## 🚀 Accédez aux Solutions Complètes !

<div align="center" style="background: linear-gradient(135deg, #6e8efb, #a777e3); padding: 30px; border-radius: 15px; color: white; margin: 40px 0; border: 3px solid #4a6cf7;">
<h2 style="color: white; font-size: 2em; margin-bottom: 15px;">✨ Solutions des Exercices Pandas</h2>
<p style="font-size: 1.1em; margin-bottom: 25px;">Code complet avec explications et données exemples</p>

<a href="https://github.com/FOFANA-Lamine/exam_final_pandas.ipynb" target="_blank" style="display: inline-block; background: white; color: #4a6cf7; padding: 15px 40px; border-radius: 50px; text-decoration: none; font-size: 1.2em; font-weight: bold; margin: 10px; box-shadow: 0 6px 20px rgba(0,0,0,0.2); transition: all 0.3s ease;">
La solution 
</a>
</div>



<div style="background: #e8f4fd; padding: 25px; border-radius: 12px; margin: 25px 0; border-left: 6px solid #4a6cf7;">
<h3>📝 Structure des Solutions</h3>
<pre style="background: white; padding: 15px; border-radius: 8px;">
# Pour chaque partie de l'exercice :
✅ Version commentée (pédagogique)
✅ Version optimisée (production)
✅ Exports prêts à l'emploi
</pre>
</div>

<div style="display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 15px; margin: 25px 0;">
<div style="text-align: center; padding: 15px; background: white; border-radius: 8px; box-shadow: 0 3px 10px rgba(0,0,0,0.1);">
<div style="font-size: 2em;">📊</div>
<div style="font-weight: bold; color: #4a6cf7;">Analyse Complète</div>
<div style="font-size: 0.9em; color: #666;">5 parties détaillées</div>
</div>

<div style="text-align: center; padding: 15px; background: white; border-radius: 8px; box-shadow: 0 3px 10px rgba(0,0,0,0.1);">
<div style="font-size: 2em;">⚡</div>
<div style="font-weight: bold; color: #10b981;">Optimisation</div>
<div style="font-size: 0.9em; color: #666;">Types de données</div>
</div>

<div style="text-align: center; padding: 15px; background: white; border-radius: 8px; box-shadow: 0 3px 10px rgba(0,0,0,0.1);">
<div style="font-size: 2em;">📈</div>
<div style="font-weight: bold; color: #f59e0b;">Visualisations</div>
<div style="font-size: 0.9em; color: #666;">Graphiques intégrés</div>
</div>

<div style="text-align: center; padding: 15px; background: white; border-radius: 8px; box-shadow: 0 3px 10px rgba(0,0,0,0.1);">
<div style="font-size: 2em;">🔗</div>
<div style="font-weight: bold; color: #8b5cf6;">Jointures</div>
<div style="font-size: 0.9em; color: #666;">SQL-like avancées</div>
</div>
</div>

<div style="background: #f0fdf4; padding: 25px; border-radius: 12px; margin: 25px 0; border: 2px solid #86efac;">
<h3>🤝 Contribuer</h3>
<p>Forkez le repository, créez une branche, et proposez vos améliorations !</p>
</div>



<div align="center" style="margin-top: 50px; padding: 20px; background: #f8f9fa; border-radius: 10px;">
<a href="https://github.com/FOFANA-Lamine/Notebook" target="_blank" style="display: inline-flex; align-items: center; gap: 10px; background: #333; color: white; padding: 12px 30px; border-radius: 8px; text-decoration: none; font-weight: bold; margin-top: 15px;">
⭐ Star sur GitHub
</a>
</div>

🔗 Lien direct : https://github.com/FOFANA-Lamine/Notebook

## 🎯 Conclusion - Votre Parcours Pandas

<div align="center" style="background: linear-gradient(135deg, #1e3c72, #2a5298); padding: 40px; border-radius: 15px; color: white; margin: 40px 0;">
<h1 style="color: white; font-size: 2.5em; margin-bottom: 20px;">✨ Félicitations !</h1>
<h2 style="color: #fbbf24; font-weight: 300; margin-top: 0;">Vous maîtrisez maintenant Pandas</h2>
</div>

📈 Votre Progression en Résumé
<div style="display: grid; grid-template-columns: repeat(auto-fit, minmax(300px, 1fr)); gap: 20px; margin: 30px 0;">
<div style="background: #f0fdf4; padding: 25px; border-radius: 10px; border: 2px solid #86efac;">
<h3>🎓 Début</h3>
<ul>
<li>✅ Structures Series et DataFrame</li>
<li>✅ Lecture/écriture de données</li>
<li>✅ Sélection et indexation</li>
</ul>
</div>

<div style="background: #eff6ff; padding: 25px; border-radius: 10px; border: 2px solid #60a5fa;">
<h3>🚀 Intermédiaire</h3>
<ul>
<li>✅ Manipulation des données</li>
<li>✅ Agrégation et regroupement</li>
<li>✅ Gestion des valeurs manquantes</li>
<li>✅ Données temporelles</li>
</ul>
</div>

<div style="background: #fef3c7; padding: 25px; border-radius: 10px; border: 2px solid #f59e0b;">
<h3>🏆 Avancé</h3>
<ul>
<li>✅ Jointures complexes SQL-like</li>
<li>✅ Optimisation mémoire</li>
<li>✅ Chaînage de méthodes</li>
<li>✅ Projet complet d'analyse</li>
</ul>
</div>
</div>

🌟 Ce Que Vous Savez Maintenant Faire
- **📊 Analyse exploratoire** : Découverte automatique d'insights
- **🔧 Nettoyage de données** : Pipelines robustes de prétraitement
- **📈 Agrégations avancées** : Statistiques par groupes multiples
- **💾 Gestion mémoire** : Traitement de gros datasets
- **📤 Reporting** : Export de résultats professionnels

💼 Applications Professionnelles
<div style="background: #f8fafc; padding: 25px; border-radius: 12px; margin: 25px 0;">
<table style="width: 100%; border-collapse: collapse;">
<tr style="background: #3b82f6; color: white;">
<th>Métier</th>
<th>Applications</th>
<th>Impact</th>
</tr>
<tr style="background: #f8fafc;">
<td>Data Analyst</td>
<td>Reporting automatisé, KPI tracking</td>
<td>Analyse 10× plus rapide</td>
</tr>
<tr style="background: #f1f5f9;">
<td>Data Scientist</td>
<td>Préparation de données, Feature engineering</td>
<td>80% du temps gagné</td>
</tr>
<tr style="background: #f8fafc;">
<td>Business Analyst</td>
<td>Analyse ventes, Performance produits</td>
<td>Décisions data-driven</td>
</tr>
</table>
</div>

🤝 Partagez Votre Travail !
<div style="background: #e8f4fd; padding: 30px; border-radius: 15px; text-align: center; margin: 40px 0; border: 3px dashed #4a6cf7;">
<h3>🎨 Montrez vos projets !</h3>
<p>
<strong>GitHub</strong> : Portfolio d'analyses<br>
<strong>LinkedIn</strong> : Partages d'insights<br>
<strong>Kaggle</strong> : Compétitions data science<br>
</p>
<p style="color: #4a6cf7; font-weight: bold;">
#PandasMaster #DataAnalysis #Python
</p>
</div>

🏆 Derniers Conseils
<div style="display: grid; grid-template-columns: repeat(auto-fit, minmax(250px, 1fr)); gap: 15px; margin: 30px 0;">
<div style="text-align: center; padding: 20px; background: linear-gradient(135deg, #667eea, #764ba2); color: white; border-radius: 10px;">
<div style="font-size: 2.5em;">⚡</div>
<div style="font-size: 1.2em; font-weight: bold;">Pratiquez Constamment</div>
<div>Traitez des données réelles quotidiennement</div>
</div>

<div style="text-align: center; padding: 20px; background: linear-gradient(135deg, #f093fb, #f5576c); color: white; border-radius: 10px;">
<div style="font-size: 2.5em;">🔍</div>
<div style="font-size: 1.2em; font-weight: bold;">Explorez la Documentation</div>
<div>Pandas évolue constamment</div>
</div>

<div style="text-align: center; padding: 20px; background: linear-gradient(135deg, #4facfe, #00f2fe); color: white; border-radius: 10px;">
<div style="font-size: 2.5em;">🎯</div>
<div style="font-size: 1.2em; font-weight: bold;">Spécialisez-vous</div>
<div>Time series, ML, Big Data...</div>
</div>
</div>

<div align="center" style="margin-top: 50px; padding: 30px; background: linear-gradient(to right, #0f2027, #203a43, #2c5364); color: white; border-radius: 15px;">
<h2 style="color: white;">✨ Votre Voyage Continue ✨</h2>
<p style="font-size: 1.1em; max-width: 800px; margin: 20px auto;">
<strong>Pandas n'est qu'un outil, votre créativité est la clé.</strong><br>
Chaque analyse que vous réalisez révèle des insights,<br>
chaque dataset que vous nettoyez devient exploitable,<br>
chaque rapport que vous générez influence des décisions.
</p>
<p style="font-size: 1.2em; font-weight: bold; color: #fbbf24;">
"Dans un monde de données, Pandas est votre super-pouvoir."
</p>
</div>

<div align="center" style="margin-top: 40px; color: #666; font-size: 0.9em;">
"Le véritable pouvoir ne réside pas dans les données,<br>mais dans notre capacité à les comprendre et à les transformer."
</div>